-- seed/capital-gains-tax-calculator.sql
-- Run in the Supabase SQL editor once the project is connected.
-- Uses dollar-quoting ($body$...$body$ and $faq$...$faq$) throughout so
-- apostrophes in the copy never need manual escaping.

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'capital-gains-tax-calculator',
  'en',
  'Nigeria Capital Gains Tax Calculator 2026 (Shares & Property)',
  'Estimate capital gains tax on shares, property, or other assets under the Nigeria Tax Act 2025 — including the ₦150m/₦10m share exemption and PPR relief.',
  'Free Nigeria capital gains tax calculator for 2026. Estimate CGT on shares, property and other disposals under the Nigeria Tax Act 2025, including exemptions and reliefs.',
  'How Capital Gains Tax Works in Nigeria Under the 2026 Tax Reform',
$body$Capital gains tax in Nigeria changed more on 1 January 2026 than almost any other part of the tax system. The old Capital Gains Tax Act, which had governed disposals of chargeable assets for decades under a flat 10% rate, was repealed outright. In its place, the Nigeria Tax Act (NTA) 2025 folds capital gains into the mainstream income tax system, so gains are no longer taxed as a separate category with their own flat rate. Instead, an individual's chargeable gain is added to their other income for the year and taxed at the same progressive Personal Income Tax (PIT) bands that apply to salary, so a modest gain sitting on top of a modest income can attract very little tax, while a large gain on top of a high income can be taxed at up to 25%. Companies see a similar realignment: the CGT rate for corporate disposals now matches the standard Companies Income Tax rate of 30%, up from the old flat 10%, though small companies are fully exempt.

The starting point for any capital gains calculation is the chargeable gain itself, and the mechanics of working it out have not changed conceptually even though the rate structure has. You take your disposal proceeds, the amount you actually received or the market value of the asset if it was not a straightforward cash sale, and deduct your allowable costs. Allowable costs include what you originally paid to acquire the asset, incidental costs of that acquisition such as legal fees, stamp duties and survey costs, any capital improvements that added lasting value to the asset, and incidental costs of the disposal itself such as agent commissions and valuation fees. Where an asset was used in a business and capital allowances were claimed against it, the tax-adjusted written-down value stands in for the original cost rather than the full purchase price, which tends to push the chargeable gain higher for depreciated business assets. Whatever is left after all of that, if positive, is your chargeable gain; if the deductions exceed the proceeds, you have a capital loss instead, which can generally be offset against gains of the same class rather than triggering a tax refund.

Shares in Nigerian companies get the most attention under the new rules because of a dedicated small-investor exemption, and this is also where the numbers have moved the most. Under the Finance Act 2021 regime that applied before 2026, a disposal was exempt if aggregate proceeds across a rolling 12-month period stayed under ₦100 million. The Nigeria Tax Act 2025 raises that proceeds threshold to ₦150 million and adds a second condition: the aggregate chargeable gain across the same 12-month period must not exceed ₦10 million. Both conditions have to be satisfied together, so a large-volume trader who technically stays under ₦150 million in proceeds but nets more than ₦10 million in gains will still fall into the taxable bracket. The 12-month window is genuinely rolling, not tied to a calendar or fiscal year, so spreading disposals further apart can matter for anyone close to the line. Separately, if disposal proceeds from shares are reinvested within the same year of assessment into shares of the same or another Nigerian company, that portion of the gain is exempt in proportion to what was reinvested, which gives active portfolio managers a legitimate way to defer tax by staying invested in the Nigerian market rather than a way to avoid it outright, since gains not reinvested remain fully chargeable.

Property disposals follow a different logic built around one long-standing relief: the Principal Private Residence exemption. Gains on an individual's main dwelling house, together with up to one acre of adjoining land, are exempt from capital gains tax, on the basis that taxing the sale of someone's actual home would be poor policy regardless of how the wider CGT regime is structured. This relief is generally understood to apply once per taxpayer to their genuine primary residence rather than to every property someone happens to live in briefly, so investment properties, rental properties and second homes do not qualify even if the owner has stayed in one of them at some point. Inherited property is treated on the basis of its value at the date of inheritance rather than what the original owner paid for it decades earlier, which matters considerably for older family properties where the historical purchase price bears little relation to current market value.

For companies, the alignment with the 30% Companies Income Tax rate is softened by the same small-company exemption that already applies to CIT itself: a company with annual turnover of ₦100 million or less and total fixed assets of ₦250 million or less is exempt not just from CIT but from capital gains tax and the Development Levy as well. This is a meaningful concession for small and growing Nigerian businesses that occasionally dispose of an asset, a piece of equipment, a vehicle, a small property, without triggering a tax bill that a company of that size might not budget for. Larger companies pay the full 30% on the chargeable gain with no equivalent small-gain carve-out the way individuals and small shareholders have.

None of this replaces proper professional advice, and several areas the Nigeria Tax Act 2025 touches on, indirect offshore transfers of Nigerian company shares, rollover relief when a business asset is replaced, and multi-year loss carry-forwards, go beyond what a straightforward calculator can reliably model. If your situation involves any of those, or a disposal size large enough that getting the number wrong would be costly, a tax adviser familiar with the NTA 2025 and the Nigeria Revenue Service's current guidance is worth the consultation. Keep your acquisition documents, valuations and disposal records regardless, since documentation, not estimation, is what the tax authority will ultimately ask for.$body$,
$faq$[
    {"q": "What is the capital gains tax rate in Nigeria in 2026?", "a": "There is no single flat rate anymore. Individuals pay CGT at the same progressive Personal Income Tax bands as their salary (0% to 25%), with the gain added on top of other income. Companies pay 30%, aligned with the standard Companies Income Tax rate, unless they qualify as a small company (turnover \u2264 \u20a6100 million and fixed assets \u2264 \u20a6250 million), in which case they are exempt."},
    {"q": "How much can I sell in shares before paying capital gains tax?", "a": "Share disposals are exempt if your aggregate proceeds across any rolling 12-month period stay under \u20a6150,000,000 AND your aggregate chargeable gain in that same period does not exceed \u20a610,000,000. Both conditions must be met; if either threshold is crossed, the disposal becomes taxable."},
    {"q": "Do I pay capital gains tax when I sell my house?", "a": "Not if it is your Principal Private Residence \u2014 your main dwelling house plus up to 1 acre of adjoining land is exempt from CGT. Investment properties, rental properties, and second homes generally do not qualify for this relief."},
    {"q": "What happens if I reinvest my share sale proceeds?", "a": "If you reinvest disposal proceeds from shares into shares of the same or another Nigerian company within the same year of assessment, the corresponding portion of your gain is exempt. Any proceeds not reinvested remain fully chargeable to tax."},
    {"q": "Is capital gains tax still a flat 10% like before?", "a": "No. The old flat 10% rate under the repealed Capital Gains Tax Act ended on 31 December 2025. From 1 January 2026, the Nigeria Tax Act 2025 taxes individual gains at progressive PIT rates and company gains at the 30% CIT-aligned rate."},
    {"q": "How is the cost base calculated for an inherited property?", "a": "For inherited assets, the cost base is generally the market value of the property at the date of inheritance, not what the original owner paid for it. This can significantly reduce the taxable gain on long-held family property."},
    {"q": "Does this calculator account for capital losses or rollover relief?", "a": "No. This tool estimates the tax on a single disposal based on the core chargeable gain formula and the main exemptions (share threshold, reinvestment relief, PPR). It does not model loss carry-forwards, rollover relief on replaced business assets, or indirect offshore transfer rules \u2014 for those, consult a tax professional."},
    {"q": "Is this calculator a substitute for filing my capital gains tax return?", "a": "No. This is an educational estimator only. Actual CGT computation, documentation, and filing should go through a licensed accountant or tax adviser and be confirmed against current Nigeria Revenue Service (NRS/FIRS) guidance."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
