-- seed/ghana-ssnit-contribution-pension-calculator.sql
insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'ghana-ssnit-contribution-pension-calculator',
  'en',
  'SSNIT Calculator 2026 — Ghana SSNIT Contribution & Pension Calculator',
  'A free SSNIT calculator for Ghana: enter your basic salary to see your SSNIT contribution split (Tier 1, Tier 2, NHIA), then estimate your monthly SSNIT pension from your contribution months and retirement age.',
  'Free Ghana SSNIT calculator. Work out your SSNIT contribution (employee, employer, self-employed) and estimate your SSNIT pension under Act 766, using current 2026 rates and insurable earnings limits.',
  'SSNIT Calculator: How Your Ghana Social Security Contribution and Pension Are Actually Worked Out',
$body$Every payslip in Ghana with a SSNIT line on it is really describing three separate things at once — a mandatory deduction taken today, a health-insurance transfer you never see, and a pension entitlement you're building for decades from now — and almost nobody outside payroll and HR actually sees how those three pieces connect. This SSNIT calculator exists to make that connection visible: enter your basic salary once, and it shows exactly how the Social Security and National Insurance Trust splits your contribution, then lets you project what that contribution history is worth as a monthly pension.

Start with what SSNIT actually is. The Social Security and National Insurance Trust is the statutory body that administers Ghana's basic national social security scheme — the mandatory, defined-benefit "Tier 1" pension every formal-sector employee and increasingly every self-employed contributor in Ghana pays into under the National Pensions Act, 2008 (Act 766), as amended by Act 883. It sits alongside, but is legally distinct from, the privately managed Tier 2 occupational pension schemes and voluntary Tier 3 provident funds that make up Ghana's three-tier pension architecture. When people search for a SSNIT calculator, a SSNIT contribution calculator, or simply "ssnit," they are usually trying to answer one of two questions this tool answers directly: how much is being deducted right now, and what will that translate to at retirement.

The contribution mechanics are simpler than most people assume, but the split matters. Contributions are calculated on basic salary only — allowances, transport, and other benefits are excluded from the base — and the total mandatory rate is 18.5%: 5.5% deducted from the employee, and 13% paid on top by the employer, so the employee never sees the employer's share leave their own pocket even though it's calculated on their salary. Of that combined 18.5%, 13.5% is remitted to SSNIT itself as the Tier 1 contribution, and the remaining 5% is forwarded to the member's Tier 2 occupational scheme, managed by a private trustee licensed by the National Pensions Regulatory Authority rather than by SSNIT. SSNIT then splits its own 13.5% further: 11% is retained to fund the Tier 1 pension, and 2.5% is passed on to the National Health Insurance Authority. This is why a basic SSNIT pension calculator has to model more than one rate — the 5.5%/13% split most people know is only the starting point of where the money actually goes.

For anyone outside formal employment, SSNIT's SEED scheme lets self-employed and informal-sector workers contribute voluntarily — 13.5% of a declared monthly income, with no employer share and, ordinarily, no automatic Tier 2 allocation, since there's no employer to split the 18.5% with. This calculator treats self-employed contributors as a distinct path for exactly that reason, rather than forcing the same 5.5%/13% employee-employer split onto someone paying the whole amount themselves.

Insurable earnings are capped and floored, and both limits move the actual cedi amount even when the percentage rates stay fixed. For 2026, the minimum insurable earnings — aligned to the national daily minimum wage — sit at roughly GHS 587.80 a month, and the maximum is GHS 69,000 a month, which caps the maximum Tier 1 remittance at GHS 9,315. Anyone earning below the floor has their contribution calculated on the floor rather than their actual (lower) salary, and anyone above the ceiling has contributions capped at the maximum rather than scaling with their full income. Because SSNIT and NPRA review these limits annually, a SSNIT contribution calculator built on last year's numbers will quietly under- or over-state what's actually being deducted — this tool uses the current 2026 figures and flags whenever your input falls outside them.

The pension side is where most confusion sits, because unlike the contribution math, the pension formula depends on two things a payslip never shows: your accumulated contribution months, and your average basic salary across your best 36 consecutive months, not simply your current or final salary. Under Act 766, a full pension requires age 60 with at least 180 contribution months — 15 years — and pays out at a "pension right" that starts at 37.5% of that best-36-month average at exactly 180 months, then rises by 0.09375% for every additional month contributed, capping at 60% once you reach 420 months, or 35 years. A reduced, early pension is available from age 55 through 59 with the same 180-month minimum, but it's scaled down by an early-retirement factor — 60% of the full pension at exactly 55, rising in steps to 90% at 59 — which this SSNIT pension calculator applies automatically once you set a retirement age below 60. Fall short of 180 months at retirement, and Act 766 doesn't pay a monthly pension at all — instead you're entitled to a lump-sum refund of your own contributions plus prescribed interest, a materially different outcome this tool flags explicitly rather than quietly returning a wrong pension figure.

Used together, the two halves of this SSNIT benefits calculator answer the question most people actually have: not just "how much is coming out of my pay this month," but "is what's coming out actually going to be enough, on the timeline I'm planning around." The figures here are a projection using the published Act 766 formula and current 2026 rates — SSNIT indexes pensions annually after they start, and your final entitlement is always determined by SSNIT from your actual certified contribution record, not by any calculator.$body$,
$faq$[
  {"q": "What is SSNIT and who has to contribute?", "a": "SSNIT (Social Security and National Insurance Trust) administers Ghana's mandatory Tier 1 basic national social security pension scheme under the National Pensions Act, 2008 (Act 766). Formal-sector employees and their employers must contribute; self-employed and informal-sector workers can contribute voluntarily through SSNIT's SEED scheme."},
  {"q": "How much do I contribute to SSNIT?", "a": "Employees pay 5.5% of basic salary, matched by a 13% employer contribution, for a mandatory 18.5% total. Of that, 13.5% is remitted to SSNIT (11% retained for the pension, 2.5% passed to NHIA) and 5% goes to your Tier 2 occupational scheme with a private, NPRA-licensed trustee, not SSNIT."},
  {"q": "How does SSNIT work for self-employed people?", "a": "Through the SEED scheme, self-employed and informal-sector contributors pay 13.5% of a declared monthly income directly to SSNIT's Tier 1 fund, with no employer share and no automatic Tier 2 allocation."},
  {"q": "What are the 2026 SSNIT insurable earnings limits?", "a": "The 2026 minimum insurable earnings is approximately GHS 587.80 a month and the maximum is GHS 69,000 a month, capping the maximum Tier 1 remittance to SSNIT at GHS 9,315. Contributions on income outside this range are calculated on the floor or ceiling, not the actual salary."},
  {"q": "How many months do I need to contribute to get a SSNIT pension?", "a": "At least 180 contribution months (15 years). Below that, retirement entitles you to a lump-sum refund of your contributions plus prescribed interest instead of a monthly pension."},
  {"q": "How is the SSNIT pension amount calculated?", "a": "Monthly pension = average of your best 36 consecutive months' basic salary × your pension right percentage. Pension right starts at 37.5% at 180 months and rises 0.09375% per additional month, capping at 60% after 420 months (35 years)."},
  {"q": "Can I retire and collect SSNIT pension before age 60?", "a": "Yes — a reduced early pension is available from age 55 to 59 with the same 180-month minimum, scaled by an early-retirement factor: 60% of the full pension at 55, rising to 90% at 59. Full, unreduced pension requires age 60."},
  {"q": "Is this SSNIT calculator official?", "a": "No. It applies the published Act 766 formula and current 2026 SSNIT/NPRA rates and limits for estimation purposes only. It is not a substitute for an official SSNIT statement — verify your actual contribution history and pension projection with SSNIT directly."}
]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
