-- seed/nigeria-rental-yield-roi-calculator.sql
-- Run in the Supabase SQL editor once the project is connected.
-- Uses dollar-quoting throughout so apostrophes in the copy never need
-- manual escaping (Postgres treats a backslash in a standard string
-- literal as a literal backslash, not an escape character).

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-rental-yield-roi-calculator',
  'en',
  'Rental Yield & ROI Calculator for Nigeria (Gross, Net & Cash-on-Cash)',
  'Enter a property price, monthly rent, and expenses to get gross yield, net yield, cash-on-cash ROI, and a multi-year return projection for Nigerian rental property.',
  'Free Nigeria rental yield and ROI calculator. Get gross yield, net yield after expenses, cash-on-cash return, and a 1-10 year projection for Lagos, Abuja, and beyond.',
  'How to Actually Calculate Rental Yield and ROI on Nigerian Property',
$body$Every landlord in Lagos, Abuja, or Port Harcourt has heard the same pitch: a property "pays for itself" at a certain rent, or a new estate promises returns that sound too good to check. The trouble is that most of those numbers only ever look at gross rent against purchase price, which flatters almost any property and hides the costs that actually determine whether an investment works. A calculator that only shows gross yield is answering the wrong question. What a serious investor needs is the net picture: rent after realistic vacancy, after the expenses that come with owning property in Nigeria specifically, and after the cash that actually left their account to acquire the asset in the first place.

Gross rental yield is the easiest number to compute and the least useful on its own. It is simply annual rent divided by purchase price, expressed as a percentage. A property renting for 850,000 naira a month against a 95 million naira purchase price shows a gross yield a little above 10 percent, which looks attractive until the running costs are subtracted. Net yield corrects for that by deducting a full year of realistic operating costs from the rent before dividing by the purchase price: maintenance and repairs, typically budgeted at somewhere around 8 to 12 percent of rent; management or agency fees, another 5 to 10 percent if the landlord isn't self-managing; service charges and estate levies not already covered by the tenant; insurance; and the Land Use Charge or equivalent state property tax. A property that shows an attractive gross yield can still be a mediocre investment once those costs are subtracted, which is exactly why comparing gross and net side by side matters more than either number alone.

Location changes both the benchmark and the cost structure. Lagos carries the country's highest Land Use Charge burden, governed by the Land Use Charge Law and its 2018 amendment, which set a materially higher annual charge rate for a residential property that is rented out or not solely occupied by its owner than for owner-occupied property. In practice this means an investment property in Lekki, Ikoyi, or Victoria Island carries a heavier annual tax load than the same-value home an owner lives in personally, which is one reason prime Lagos rental yields tend to sit lower, often in the four to seven percent range, than Lagos Mainland or Abuja, where yields more commonly land in the six to nine percent band. Abuja and other states run their own tenement-rate style charges, generally lower and less standardised in how they're published, which is why this calculator treats the Land Use Charge line as an editable estimate tied to your selected location rather than a fixed figure — always check your own state's Land Use Charge notice or portal for the actual assessed amount, since it's based on an independently assessed market value rather than the purchase price used here.

Withholding tax is another line that trips people up because it depends on who the tenant is, not where the property sits. Under the Nigeria Tax Act 2025, a 10 percent withholding tax is commonly deducted at source on rent paid by corporate tenants, meaning a company leasing office or residential space for its staff typically withholds that percentage before paying the landlord, who then reconciles it against their tax liability. Individual-to-individual tenancies, the far more common arrangement for a single rental unit, generally don't have this withheld in the same way in practice, which is why this tool makes it a toggle tied to tenant type rather than applying it automatically to every calculation.

Return on investment goes a step further than yield by accounting for how the purchase was financed and what it actually cost to acquire the property, not just its sticker price. Buying property in Nigeria carries a bundle of one-time costs on top of the purchase price: legal fees typically running 5 to 10 percent of the property value, a similar range for buyer-side agency commission, and stamp duty commonly quoted around 1.5 percent of the transaction value, on top of separate perfection and registration costs. Add renovation or furnishing spend and a down payment if financing is involved, and the true cash invested is usually well above the headline purchase price. Cash-on-cash return divides net annual income, after any loan interest, by that total cash invested, which is why two properties with an identical net yield can show very different ROI once one is bought with a mortgage and the other with cash.

Projecting returns over several years adds a final, honest layer: expected capital appreciation compounded against the purchase price, combined with several years of net rental income, measured against the cash actually invested. Nigerian property appreciation varies sharply by location and market cycle, which is why the projection here uses an editable annual rate rather than a single fixed assumption, and why cumulative income is held flat at year-one levels rather than assumed to grow, a conservative choice that keeps the numbers auditable rather than optimistic. None of this replaces professional advice from a licensed estate surveyor, a property lawyer, or your state's internal revenue service before committing real money, but it does turn a vague "good investment" pitch into a set of numbers you can actually interrogate.$body$,
$faq$[
    {"q": "What is a good rental yield in Nigeria?", "a": "It depends heavily on location. Prime Lagos areas like Lekki, Ikoyi, and Victoria Island typically show gross yields of roughly 4 to 7 percent because purchase prices are high relative to achievable rent, while Lagos Mainland and Abuja more commonly land in the 6 to 9 percent range, and other states can run higher still. Net yield after expenses is always lower than gross, so compare like with like."},
    {"q": "What is the difference between gross yield and net yield?", "a": "Gross yield is simply annual rent divided by purchase price. Net yield subtracts a full year of realistic operating costs first, including maintenance, management or agency fees, service charges, insurance, and Land Use Charge or equivalent property tax, before dividing by the purchase price, which gives a far more honest picture of what the property actually returns."},
    {"q": "Does withholding tax apply to all rental income in Nigeria?", "a": "Not automatically. A 10 percent withholding tax is commonly deducted at source under the Nigeria Tax Act 2025 when the tenant is a company, but individual-to-individual tenancies generally don't have it withheld in the same way in practice, which is why this calculator only applies it when you indicate a corporate tenant."},
    {"q": "How much is the Land Use Charge on a rental property in Lagos?", "a": "The Land Use Charge Law, as amended in 2018, sets a materially higher annual charge rate for a rented or non-owner-occupied residential property than for one the owner lives in, applied to an independently assessed market value rather than the purchase price. This calculator estimates it as a share of purchase price by location as a starting point, but you should confirm the actual figure with your Land Use Charge notice or the LIRS portal."},
    {"q": "What extra costs should I budget for when buying rental property in Nigeria?", "a": "Beyond the purchase price, budget for legal fees and buyer-side agency commission, each commonly 5 to 10 percent of the property value, stamp duty around 1.5 percent, and separate perfection or registration costs. These one-time costs are added to your down payment to determine your true total cash invested, which is what cash-on-cash return is measured against."},
    {"q": "How is cash-on-cash ROI different from rental yield?", "a": "Rental yield measures income against the property's purchase price alone. Cash-on-cash ROI measures net income, after any loan interest, against the actual cash you put in: your down payment plus all one-time purchase costs. A financed property and a cash-purchased property with identical net yield can show very different cash-on-cash returns."},
    {"q": "Can I use this calculator for a property outside Lagos or Abuja?", "a": "Yes. Select 'Other Nigeria' as the location for a lower default Land Use Charge and appreciation estimate, and adjust any of the expense or cost fields to match your specific state and property, since every input in this tool is editable."},
    {"q": "Does the projection assume rent will increase over time?", "a": "No, deliberately not. To keep the numbers conservative and auditable, cumulative net income in the multi-year projection is held flat at year-one levels rather than grown annually, while only the property's capital value is compounded by your chosen appreciation rate. In an inflationary market this likely understates real returns, since rents typically rise over a multi-year hold."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
