-- seed/nigeria-cac-registration-calculator.sql
-- Run in the Supabase SQL editor once the project is connected.

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-cac-registration-calculator',
  'en',
  'CAC Registration Cost Calculator Nigeria 2026 (Business Name vs Ltd)',
  'Estimate CAC registration costs for a business name, private company, company limited by guarantee, or NGO in Nigeria, and compare structures side by side.',
  'Free CAC registration cost calculator for Nigeria. Compare business name vs private limited company fees, timelines, and requirements for 2026.',
  'How Much Does CAC Registration Actually Cost in Nigeria in 2026?',
$body$Ask five different sources how much it costs to register a business with Nigeria's Corporate Affairs Commission in 2026, and there is a real chance you get five different numbers. Some quote ₦10,500 for a business name. Others say ₦21,000. Some put a private limited company's base registration at ₦10,000, others at ₦40,000, a four-fold difference for what should be a fixed government fee. This is not a case of everyone else being wrong and one source being right, it more likely reflects the CAC's own fee schedule genuinely changing multiple times in a short window, a gazette revision in May 2025, a further service fee review effective August 2025, and an additional AI-powered processing charge introduced in April 2026, with different guides and agencies updating to different degrees. The honest starting point for anyone budgeting for CAC registration is to treat any single number with some skepticism and confirm the live figure on the CAC portal before paying.

With that caveat upfront, the figures that appear most consistently across recent, detailed 2026 sources look like this. A business name, the registration route for sole proprietorships and partnerships, costs ₦1,000 to reserve the name (₦5,000 if it uses a restricted word or company-style suffix) plus ₦20,000 to register, for a total of roughly ₦21,000 in official CAC fees before any portal transaction charge. A private company limited by shares, the standard structure for a business planning to scale or bring in outside shareholders, costs ₦1,000 for name reservation plus ₦40,000 in registration fees for share capital up to ₦1,000,000, with an additional ₦10,000 in CAC fees for every extra ₦1,000,000 of share capital declared. On top of the CAC fee sits a separate, federal stamp duty charged by FIRS, not CAC, at 0.75% of share capital, which adds roughly ₦7,500 on a standard ₦1,000,000 registration. As of April 2026, CAC also layers on a modest AI service charge, ₦200 on name reservation and ₦500 on registration, introduced alongside the platform's move to AI-assisted processing.

The choice between a business name and a private limited company is not primarily a pricing decision, even though the private company costs roughly twice as much upfront. It is a liability and growth decision. A business name offers no separation between you and your business: if the business owes money it cannot pay, creditors can, in principle, pursue your personal assets. A private limited company creates a distinct legal person, and shareholders generally risk only what they invested in shares. If you plan to bring on investors, apply for meaningful business financing, or simply want a firewall between business risk and personal assets, the additional cost of incorporation tends to look small next to what it protects. If you are testing an idea, working as a freelancer, or running a small local trade with no near-term plan to raise capital, a business name gets you legally recognized, able to open a corporate account, and able to sign contracts, at a fraction of the cost and paperwork.

Two other structures round out the common options. A Company Limited by Guarantee suits organizations that need corporate legal status but have no shareholders and no share capital, professional bodies, think tanks, and similar non-profit-adjacent entities, though it requires Attorney General of the Federation approval before the CAC will incorporate it, which realistically adds weeks to the timeline regardless of how quickly the CAC itself processes the filing. Incorporated Trustees is the structure NGOs, churches, mosques, and community associations use, and it carries its own procedural weight: a mandatory 28-day newspaper publication and public objection period before registration completes, on top of CAC fees that run to roughly ₦45,000 before newspaper costs, which themselves typically add another ₦20,000 to ₦30,000.

Whichever structure fits, the process itself now runs almost entirely online through the CAC's portal: search and reserve a name, which stays held for 60 days once approved, complete the relevant registration form with entity and ownership details, upload supporting documents, pay the applicable fees, and download the certificate once approved. Since 2026, incorporation also requires disclosing Persons with Significant Control, anyone owning or controlling more than 25% of the company, at the point of registration rather than as a later filing. Most delays come down to avoidable errors: blurry or black-and-white ID scans, a proposed name too close to an existing registration, or incomplete director and shareholder details. Budgeting realistically also means accounting for what falls outside CAC's own fee schedule entirely: opening a corporate bank account typically requires an initial deposit in the ₦10,000–₦20,000 range, and anyone hiring a lawyer or accredited agent rather than self-filing should expect professional fees anywhere from ₦15,000 for straightforward business name filings up to ₦220,000 for more complex company incorporations handled by a law firm.

None of the figures here should be treated as final. Fee schedules, processing charges, and even entire filing categories change with enough regularity that the single most reliable step in this entire process is confirming the live cost on the official CAC portal in the same session you intend to pay.$body$,
$faq$[
    {"q": "How much does it cost to register a business name with CAC in Nigeria?", "a": "Based on the most consistent recent figures, roughly \u20a621,000 in total official fees: \u20a61,000 for name reservation (\u20a65,000 if the name uses a restricted word) plus \u20a620,000 for registration. This excludes portal transaction fees and any agent charges."},
    {"q": "How much does it cost to register a private limited company in Nigeria?", "a": "For share capital up to \u20a61,000,000: roughly \u20a648,500 in total, made up of \u20a61,000 name reservation, \u20a640,000 CAC registration fee, and \u20a67,500 FIRS stamp duty (0.75% of share capital). Each additional \u20a61,000,000 of share capital adds about \u20a610,000 in CAC fees plus 0.75% stamp duty."},
    {"q": "Why do different websites quote such different CAC registration fees?", "a": "The CAC's fee schedule has changed multiple times in a short window \u2014 a May 2025 gazette revision, an August 2025 service fee review, and an April 2026 AI service charge \u2014 and different guides have updated to different degrees. Always confirm the current fee on the CAC portal before paying, rather than relying on any single published figure, including this one."},
    {"q": "Should I register a business name or a limited company?", "a": "A business name is cheaper and faster but offers no separation between you and the business \u2014 you are personally liable for its debts. A private limited company costs more upfront but limits shareholders' liability to what they invested, and is generally necessary if you plan to raise investment or bring on multiple owners."},
    {"q": "What is the minimum share capital for a private company in Nigeria?", "a": "CAMA 2020 sets the minimum issued share capital for a private company at \u20a6100,000, though \u20a61,000,000 is the practical figure most startups use, partly because CAC's registration fee tiers are structured around \u20a61,000,000 increments."},
    {"q": "How long does CAC registration take?", "a": "A business name typically takes 1\u20137 working days, often same-day to 72 hours online. A private limited company typically takes 3\u201314 working days. Incorporated Trustees (NGOs) take significantly longer, 6\u20138 weeks, due to a mandatory 28-day newspaper publication and objection period."},
    {"q": "What is the CAC AI service charge?", "a": "Effective 1 April 2026, the CAC introduced an additional processing charge alongside its move to AI-assisted platform services: \u20a6200 on name reservation and \u20a6500 on registration. This is layered on top of the base fees, not a replacement for them."},
    {"q": "Is this calculator giving me the official CAC price?", "a": "No. This is an estimate based on the most consistently reported figures across multiple public sources at the time of writing, not a live feed from CAC. Given how much published fee data currently disagrees, always verify the exact current cost on the official CAC portal (pre.cac.gov.ng) before paying."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
