-- seed/nigeria-catfish-farming-break-even-calculator.sql
insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-catfish-farming-break-even-calculator',
  'en',
  'Catfish Farming Break-Even Calculator Nigeria 2026 — Profit & Cost Calculator',
  'A free catfish farming break-even calculator for Nigeria: enter your stocking, feed, and cost figures to see break-even price per kg, cost of production, ROI, and profit margin for your grow-out cycle.',
  'Calculate catfish farming profit and break-even cost in Nigeria. Free tool for fish farming in Lagos, Ibadan, and nationwide — covers feed cost, FCR, survival rate, and farm-gate selling price.',
  'Catfish Farming Break-Even Calculator: What It Really Costs to Turn a Profit in Nigeria',
$body$Catfish farming in Nigeria looks deceptively simple from the outside — stock some juveniles, feed them for a few months, sell at table size — but the gap between farmers who profit and farmers who barely break even almost always comes down to numbers most people never actually sit down and calculate. This catfish farming break-even calculator exists for exactly that reason: to turn survival rate, feed conversion, and farm-gate prices into a clear picture of what a cycle actually costs you, and what price you need to hit just to cover it.

Start with why cat fish farming in Nigeria has become such a common small-business path in the first place. Clarias gariepinus — African catfish — tolerates the crowded, sometimes inconsistent water conditions of a backyard tarpaulin pond or concrete tank far better than most fish species, grows to table size in roughly 5 to 6 months, and sells into a steady, culturally embedded demand across the country. Fish farming in Lagos and fish farming in Ibadan are two of the most visible clusters — dense urban demand paired with accessible feed and fingerling supply chains — but catfish in Nigeria is realistically a nationwide business, from backyard operations feeding a single household's income to medium commercial setups running several thousand fish per cycle.

The biology drives the economics more directly here than in most livestock enterprises, so the calculator starts there. Stock a known number of fingerlings or juveniles, apply a realistic survival rate — 80–90% is achievable with decent water management and biosecurity, with 85% a sensible planning default — and that gives you your harvested fish count. Multiply by an average harvest weight, typically 1.0 to 1.2kg at table size, and you have your total harvest weight in kilograms, which is the number every cost and revenue figure downstream actually depends on.

Feed is where catfish farming profit is won or lost, which is why how much to start catfish farming calculator searches so often circle back to feed cost specifically. Feed typically accounts for 60% to 70%-plus of total operating cost, and the driver behind that cost is the feed conversion ratio (FCR) — how many kilograms of feed it takes to produce one kilogram of fish. A well-managed pond on quality floating feed runs an FCR of roughly 1.2 to 1.5; poorer management, or switching to cheaper sinking or local feed, pushes that ratio — and your total feed bill — considerably higher. A 15kg bag of mid-range floating feed commonly costs ₦22,000 to ₦36,000 in the current Nigerian market, and for a standard 1,000-fish cycle, total feed consumption often lands between 1.0 and 1.4 tonnes. This calculator lets you compute feed cost automatically from FCR and price per kilogram, or enter a known total directly if you already have supplier quotes.

Beyond feed, the remaining catfish farming cost in Nigeria breaks into a handful of predictable categories: fingerlings or juveniles, typically ₦40 to ₦100 each depending on quality and source; pond or tank setup, where a tarpaulin pond is the cheapest entry point and concrete construction costs considerably more but lasts longer; labour; water, pumping, and electricity or fuel for aeration and circulation; medications and water-quality treatments; and transport, marketing, and harvesting costs. None of these individually rivals feed, but together they shape whether a cycle that looks profitable on paper for a catfish farm in Nigeria actually is once every line item is accounted for.

Revenue is the other half of the equation, and it hinges on the farm-gate selling price per kilogram — the price a farmer actually receives, not the retail price a consumer eventually pays. That figure runs roughly ₦2,500 to ₦3,500 per kilogram depending on season, size, and buyer — market women typically pay less than restaurants and direct retail buyers — with Lagos and Abuja averaging around ₦3,000/kg in early 2026. This calculator uses your entered price to work out gross revenue, and from there, the numbers that actually answer "is this worth doing": net profit or loss, profit margin, return on investment, cost of production per kilogram, and — the core of any catfish break-even calculator — the break-even selling price per kilogram and the minimum number of fish you need to sell to cover your total cost.

Because feed prices and selling prices both move with fuel costs, FX rates, and seasonal demand, this tool also runs a simple sensitivity check — what happens to your profit if feed price rises or falls 20%, or if your selling price shifts 10% in either direction. That's often the single most useful output for anyone building a catfish business plan in Nigeria, because it shows how much cushion (or how little) sits between your current plan and a loss-making cycle.

Whether you're sizing up your first 500-fish tarpaulin pond or scaling a medium 3,000-fish concrete-tank operation, this calculator is built to answer the question every serious catfish farmer eventually has to answer with real numbers, not optimism: at what price, and at what volume, does this cycle actually pay for itself.$body$,
$faq$[
  {"q": "How much does it cost to start catfish farming in Nigeria?", "a": "For a standard 1,000-fish cycle, expect roughly ₦100,000–₦180,000 for fingerlings and setup combined, plus feed as the dominant ongoing cost — often 60–70% of total spend. This calculator lets you enter your own stocking size, feed price, and setup cost to get an exact figure for your scale, from a small 500-fish start to a medium 3,000-fish operation."},
  {"q": "How much feed does 1,000 catfish need?", "a": "Total feed for 1,000 stocked fish commonly runs 1.0 to 1.4 tonnes across a 5–6 month cycle, depending on your feed conversion ratio (FCR) and survival rate. This calculator computes feed quantity automatically from your FCR and target harvest weight, or lets you enter a known total feed cost directly."},
  {"q": "What is a good FCR for catfish farming in Nigeria?", "a": "1.2 to 1.5 is typical with quality floating feed and good management. A higher FCR — meaning more feed needed per kilogram of fish produced — usually points to sinking or local feed, poor water quality, or management issues, and directly increases your cost of production per kilogram."},
  {"q": "What is the current catfish price per kg in Nigeria?", "a": "Farm-gate prices typically range ₦2,500–₦3,500 per kilogram, with Lagos and Abuja averaging around ₦3,000/kg in early 2026. Prices vary by season, fish size, and buyer type — market women generally pay less than restaurants or direct retail buyers. Enter your local price to get an accurate break-even figure."},
  {"q": "How is catfish farming break-even price calculated?", "a": "Break-even price per kg equals your total cost for the cycle (fingerlings, feed, setup, labour, water/power, medications, transport, and miscellaneous costs) divided by your total harvest weight in kilograms. Selling above that price returns a profit; selling below it means a loss regardless of volume."},
  {"q": "What survival rate should I plan for in catfish farming?", "a": "80–90% is realistic for a reasonably well-managed pond or tank, with 85% a sensible default for planning. Poor water quality, overcrowding, or disease can push survival significantly lower, which is why this calculator lets you test different survival rates against your costs."},
  {"q": "Is catfish farming in Nigeria regulated?", "a": "Small-to-medium private catfish ponds and tanks are largely unregulated beyond general business registration. Larger or more intensive commercial operations may need Corporate Affairs Commission (CAC) registration, environmental (EIA) clearance, and aquaculture licensing through the Federal Department of Fisheries & Aquaculture or your state ministry — this calculator is a pure economic tool and does not cover compliance requirements."},
  {"q": "How many catfish farming cycles can I run per year?", "a": "Two cycles a year is achievable in good conditions, since a typical grow-out cycle to table size (1.0–1.2kg) takes 5 to 6 months. This calculator's annual projection lets you adjust cycles per year to match how your pond or tank is realistically used."}
]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
