-- seed/nigeria-inflation-impact-simulator.sql
-- Run in the Supabase SQL editor once the project is connected.
-- Uses dollar-quoting throughout so apostrophes in the copy never need
-- manual escaping (Postgres treats a backslash in a standard string
-- literal as a literal backslash, not an escape character).

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-inflation-impact-simulator',
  'en',
  'Nigeria Inflation Impact Calculator: See How Inflation Erodes Your Savings',
  'Enter a naira amount and a date range to see how much real purchasing power inflation has eaten away, using NBS headline and food CPI data.',
  'Free Nigeria inflation calculator. See what your savings or salary are really worth today using NBS CPI data, with a purchasing power chart and year-by-year breakdown.',
  'What Nigeria''s Inflation Numbers Actually Do to Your Money',
$body$Every month, the National Bureau of Statistics releases a single headline number, a year-on-year percentage that Nigerians have learned to brace for, celebrate, or shrug off depending on which direction it moves. But a percentage on a press release is abstract in a way that money in a bank account is not. What most people actually want to know is much more concrete: if I leave a million naira sitting in an account, or if my salary stays flat while prices keep climbing, how much of my real spending power have I actually lost, and how much of it will be gone a year from now? That is the gap this calculator is built to close, translating NBS inflation data into a single answer, expressed in the naira terms of the year you actually care about.

The National Bureau of Statistics, established under the Statistics Act 2007 and headquartered in Abuja, is Nigeria's official statistics office and the sole authority for the country's Consumer Price Index. Every month it surveys prices for a defined basket of goods and services across all thirty-six states and the FCT, and publishes the CPI and Inflation Report a few weeks after the reference month closes. That monthly report is the single source this tool draws its historical figures from, both the headline rate covering the full basket and the food sub-index that tracks grocery and provisions prices specifically, which typically moves faster and further than the headline number because food carries such a large weight in the average Nigerian household budget.

A detail that trips up a lot of people comparing numbers across 2024 and 2025 is the CPI rebasing the NBS carried out, effective from the January 2025 report. Rebasing moved the price reference period, the base year against which every other month is measured, from 2009 to 2024, and updated the weight reference period to 2023 to reflect how Nigerian households actually spend money today rather than fifteen years ago. The exercise also expanded basket coverage to 934 product varieties across thirteen divisions under the COICOP 2018 classification framework. One visible consequence is that the headline year-on-year rate appears to fall sharply between December 2024, the last reading under the old 2009 base, and January 2025, the first reading under the new 2024 base. That drop reflects a change in measurement methodology, not a sudden one-month collapse in prices, and this calculator treats the two periods as distinct series rather than dividing raw index points across that boundary, which would produce a mathematically invalid result.

The mechanics behind the headline number matter for anyone trying to reason about their own money. Each month the NBS calculates a Laspeyres-type price index across the basket, and headline inflation is simply that index compared to the same month a year earlier. Core inflation strips out the more volatile farm produce and energy components, which is why analysts and the Central Bank of Nigeria watch it separately, since it gives a cleaner read on the underlying, stickier price pressure in the economy. None of this changes what a household actually experiences, which is why converting the percentage into naira, and into everyday items like a bag of rice or a litre of petrol, tends to communicate the effect of inflation far more directly than the rate itself.

The core arithmetic this tool performs is straightforward once the data is lined up correctly: the real value of a naira amount held from one date to another equals the nominal amount divided by how much the general price level grew over that period, with each month's published year-on-year rate converted into an equivalent monthly compounding rate and chained together across the selected range. If a nominal growth rate is added, representing a savings account, a fixed deposit, or a salary increment, the calculator compounds that growth first and then discounts the result by the same cumulative inflation factor, which is exactly how economists distinguish a nominal return from a real one. A savings account paying an attractive-looking double-digit rate can still represent a real loss if inflation over the same stretch ran higher, and seeing both numbers side by side, rather than just the bank's advertised rate, is usually the point at which the erosion becomes obvious.

This matters most acutely for anyone on a fixed naira income, whether that is a pension, a salary that has not been renegotiated in a while, or savings parked in an account earning less than the prevailing inflation rate. Each of those is, in real terms, shrinking even while the number on the account statement stays the same or grows slowly. Retirees drawing a fixed pension, workers between salary reviews, and anyone with naira-denominated savings sitting idle are the clearest cases where this gap between nominal and real value compounds into a meaningful loss over a few years, which is precisely the scenario this simulator is built to make visible rather than abstract.

None of the figures here substitute for the NBS's own monthly release, which remains the authoritative record for any specific month. What this calculator offers instead is a way to translate that monthly percentage into a concrete answer for your own numbers: how much of a given naira amount's purchasing power has actually eroded between two dates, what it would have taken in nominal growth to keep pace, and what that erosion looks like in terms of everyday goods rather than an abstract index.$body$,
$faq$[
    {"q": "Why did Nigeria's inflation rate suddenly drop in January 2025?", "a": "The NBS rebased the Consumer Price Index effective the January 2025 report, moving the base year from 2009 to 2024 and updating the basket weights to 2023 spending patterns. The apparent drop in the headline rate reflects that change in measurement methodology, not an actual one-month fall in prices, which is why this tool treats pre-2025 and post-2025 figures as separate series rather than dividing index points across that boundary."},
    {"q": "How much will 1 million naira be worth in 5 years if I just save it?", "a": "It depends entirely on the inflation rate over those five years and any interest your savings earn. Enter your amount, a start date, and an end date into the calculator above, with your savings rate if any, to see the real, inflation-adjusted value based on actual and projected NBS CPI data rather than a guess."},
    {"q": "What is the difference between headline inflation and food inflation in Nigeria?", "a": "Headline inflation tracks the full NBS consumer basket across all categories, while food inflation isolates food and non-alcoholic beverages specifically. Food typically carries a large weight in Nigerian household budgets and has often moved faster than the headline rate, which is why this tool lets you toggle between the two."},
    {"q": "Does a savings account interest rate protect me from inflation in Nigeria?", "a": "Only if the interest rate exceeds the inflation rate over the same period. If your savings account pays a nominal rate below prevailing inflation, the real, inflation-adjusted value of your balance still falls even though the naira figure on your statement is growing -- the scenario comparison in this calculator shows both outcomes side by side."},
    {"q": "How does the NBS calculate Nigeria's inflation rate?", "a": "The NBS, Nigeria's official statistics office under the Statistics Act 2007, surveys prices for a defined basket of goods and services across all states monthly and calculates a price index against a fixed base period. Headline inflation is the year-on-year change in that index; core inflation strips out the more volatile farm produce and energy components."},
    {"q": "What does 'real value' mean in this calculator?", "a": "Real value is a naira amount expressed in the purchasing power of your selected start date, after removing the effect of inflation between then and your selected end date. It answers the question, in goods and services, not just naira count, how much is this amount actually worth compared to when I started."},
    {"q": "Why does this calculator use interpolated figures for some months?", "a": "The NBS does not always publish every intermediate month at the same level of detail, particularly for the food sub-index and for the pre-2025 period under the old base year. Where a specific month is not directly published, this tool linearly interpolates between the closest known readings and flags those months in the historical table."},
    {"q": "Is this an official NBS calculator?", "a": "No. This is an independent educational tool built using publicly reported NBS CPI and inflation data. It is not affiliated with or endorsed by the National Bureau of Statistics, and for the current official inflation rate you should always check the NBS's own monthly CPI and Inflation Report."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
