insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-agro-land-planner',
  'en',
  'Nigeria Crop & Land Planner — Best Crops to Plant by State, Soil & Season',
  'Plan what to plant on your land in Nigeria based on state, soil type, season, and budget, with planting windows and yield guidance.',
  'Free Nigeria crop suitability planner. Find the best crops for your land size, state, soil, and season, with planting calendars, spacing, and legal notes.',
  'Nigeria Agro Land Planner: What Should You Actually Plant on Your Land?',
$body$Deciding what to plant is often the single most important decision a Nigerian farmer or landowner makes, and it is one that is frequently made without a clear picture of what the local climate, soil, and market actually support. An agro land planner brings together Nigeria's agro-ecological zones, standard crop calendars, and basic land-size math into one place, so anyone with a plot in Ogun, a farm in Benue, or a family holding in Kano can see, in minutes, which crops genuinely suit their land, when to plant them, and roughly what to expect at harvest.

Nigeria is broadly divided into three agro-ecological bands that most public agricultural guidance references, even though the country's full zoning system is more detailed. The South, covering the Humid Forest and Rainforest belt across the South West, South East, and South South, has high and often bimodal rainfall that supports root and tree crops particularly well — cassava, yam, cocoa, and oil palm all thrive here, and many southern states get two planting windows a year rather than one. The Middle Belt, broadly the Guinea Savannah zone anchored by states like Benue, Kogi, Niger, and Plateau, sits in between: it has a single strong rainy season long enough to support maize, soybean, and the country's most productive yam-growing areas. The North, the Sudan and Sahel zone running through Kano, Katsina, Sokoto, and neighboring states, has a shorter rainy season and lower total rainfall, which favors drought-tolerant staples such as millet, sorghum, cowpea, and groundnut, while irrigated schemes along rivers and fadama lowlands make crops like dry-season tomato and rice viable even in the dry months.

Matching a crop to a zone is only the first layer of a useful land plan. Soil type shifts suitability further within a zone — loamy soil is the most versatile and generally the best starting point for maize, yam, or soybean, sandy soil drains quickly and suits cassava or groundnut well but holds less fertility, and clay soil retains water in a way that particularly favors lowland or swamp rice. Rainfall and irrigation access matters just as much: several high-value opportunities, most notably dry-season tomato production in the Kano-Jigawa belt and irrigated rice schemes in Kebbi, are only realistic with a working irrigation source, and attempting them purely on rain-fed land in the wrong season is one of the most common ways Nigerian farmers lose an entire planting cycle.

Land size then determines the practical scale of any plan. Nigerian landholdings are commonly described in plots, acres, or hectares depending on region and context, and converting between them matters for anything beyond rough guesswork — a standard reference plot is often quoted around 465 square meters, an acre is approximately 0.4047 hectares, and most agronomic yield and spacing data, including government Agricultural Performance Survey figures, is published per hectare. Once land size is converted to hectares, it becomes straightforward to estimate how many plants, mounds, or stands a plot can hold using typical spacing figures, for example roughly 10,000 cassava plants or yam mounds per hectare versus around 53,000 maize plants at standard spacing, which in turn shapes realistic seed, sett, or seedling budgets before planting begins.

Intercropping and rotation are two of the lowest-cost ways Nigerian smallholders improve both yield stability and soil health, and they are worth planning for from day one rather than treating as an afterthought. Pairing a cereal with a legume, such as maize with cowpea or soybean, lets the legume fix nitrogen that benefits the cereal, while young tree crops like oil palm or cocoa are frequently intercropped with cassava, maize, or plantain during the several years before the canopy closes, turning otherwise idle inter-row space into an early income source. Rotating cereals with legumes season to season, rather than repeating the same crop indefinitely on the same plot, also helps restrain the buildup of soil-borne pests and diseases and reduces long-term fertilizer dependence.

Any serious land plan in Nigeria also has to account for land documentation, which is where many otherwise sound farming plans run into trouble. The Land Use Act of 1978 vests all land within a state in that state's Governor, meaning farming on any parcel requires a valid Right of Occupancy — a statutory grant for urban land, or a customary right typically obtained through the Local Government for most rural and agricultural land — and a single customary holding generally cannot exceed 500 hectares for agricultural purposes without the Governor's explicit consent. Farmers planning to operate commercially should also expect to register a Business Name or limited company with the Corporate Affairs Commission, register with the Federal Ministry of Agriculture and Rural Development to access many subsidy and grant programs, and, for larger land-development projects above roughly 500 hectares, secure an Environmental Impact Assessment before clearing begins.

None of this replaces an actual visit from an extension officer, a proper soil test, or legal confirmation of land title, all of which remain essential before committing real money to seed, land preparation, or irrigation infrastructure. What a land and crop planning tool offers instead is a fast, evidence-based starting point — narrowing dozens of possible crops down to the handful that genuinely fit a given zone, soil, season, and budget, so that the conversation with an agronomist, a State Agricultural Development Programme officer, or NAERLS extension staff starts from an informed position rather than a blank page.$body$,
$faq$[
  {"q": "What is the best crop to plant on a small farm in Nigeria?", "a": "It depends heavily on your zone — cassava and yam suit the South and Middle Belt well, while millet, sorghum, and cowpea are better matches for the drier North; soil type and season further narrow the best fit."},
  {"q": "How many plants fit on one hectare of land in Nigeria?", "a": "It varies by crop: maize is typically planted at around 53,000 plants per hectare, cassava and yam around 10,000 per hectare, while cocoa is spaced much wider at roughly 1,111 trees per hectare."},
  {"q": "How big is a standard plot of land in Nigeria?", "a": "There's no single legal definition, but a commonly used reference plot is around 465 square meters (roughly 50ft by 100ft) — always confirm the local convention, since it varies by state and estate."},
  {"q": "Can I farm on any land I own in Nigeria without extra documentation?", "a": "No — under the Land Use Act 1978, all land is vested in the state Governor, and farming requires a valid Right of Occupancy, whether statutory (urban) or customary (mostly rural, obtained through the Local Government)."},
  {"q": "What crops grow best in Northern Nigeria's dry climate?", "a": "Drought-tolerant staples like millet, sorghum, cowpea, and groundnut are best suited to the North's shorter rainy season, while irrigated schemes make dry-season tomato and rice viable in areas like Kano, Jigawa, and Kebbi."},
  {"q": "Do I need to register a business to sell crops commercially in Nigeria?", "a": "For serious commercial farming, registering a Business Name (or limited company for larger operations) with the Corporate Affairs Commission is standard practice, and it's often required to access FMARD subsidy or grant programs."},
  {"q": "What is the best crop rotation for maize in Nigeria?", "a": "Rotating maize with a nitrogen-fixing legume such as cowpea or soybean is a widely recommended low-cost practice that helps restore soil fertility and reduce pest buildup between seasons."},
  {"q": "How long does it take for cocoa or oil palm to start producing income?", "a": "Both are long-term investments — cocoa typically bears its first harvest after about 2–3 years, and oil palm after roughly 3–4 years, before settling into regular annual or continuous production."}
]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
