-- seed/nigeria-cac-annual-returns-compliance-checker.sql
-- Run in the Supabase SQL editor once the project is connected.
-- Figures corrected against CAC's official downloadable fee schedule
-- (cac.gov.ng/api/download-fees) — several numbers in the original version
-- of this article were wrong (sourced from third-party guides that turned
-- out to disagree with the official schedule), most importantly the late
-- penalty, which is a daily + one-off structure, not a flat per-year fee.

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-cac-annual-returns-compliance-checker',
  'en',
  'CAC Annual Returns Compliance Checker Nigeria 2026 (Fees & Penalties)',
  'Estimate your CAC annual returns filing fees, daily default penalties, and strike-off risk for business names, private companies, and NGOs — based on the official CAC fee schedule and CAMA 2020.',
  'Free CAC annual returns compliance checker for Nigeria. Estimate filing fees, daily late penalties, and strike-off risk for business names, companies, and NGOs under CAMA 2020.',
  'CAC Annual Returns in Nigeria: Fees, Penalties, and How Strike-Off Actually Works',
$body$Every business registered with Nigeria's Corporate Affairs Commission, whether a business name, a private company, or an incorporated trustee, has one recurring statutory obligation that outlasts the excitement of registration itself: filing annual returns. Unlike tax returns, which report income and go to the Nigeria Revenue Service, annual returns go to the CAC and confirm something narrower but still important, that the entity is still active and that its core records, directors, shareholders, registered address, are accurate. Miss enough of them, and the consequences move from a modest late fee to a genuine risk of losing the company's legal existence entirely.

The mechanics differ by entity type, and getting them mixed up is the single most common source of confusion. Business names, which cover sole proprietorships and partnerships, are expected to file annually by 30 June, with a filing fee of ₦3,000 per filing under the CAC's official fee schedule. Private companies limited by shares face a different clock: the statutory deadline is technically within 42 days of the company's Annual General Meeting, but in practice, for the many companies with a 31 December financial year-end, that translates to a working deadline around 30 June of the following year, and the filing fee is ₦5,000 per filing, whether the company qualifies as a CAMA "small company" or not, the base fee is identical either way. Public companies pay more, ₦10,000 per filing. A newly incorporated company gets some breathing room before any of this applies, generally around 18 months from incorporation before the first annual return is due, so a company registered late last year is unlikely to be overdue for anything yet even if it feels overdue.

Where company size actually matters is the penalty for defaulting, and the structure here surprises a lot of people: it is not a single flat fee charged once per missed year. The official schedule sets out two separate components. First, a daily default penalty that accrues for every day an entity stays out of compliance, ₦250 a day for a CAMA-defined small company, ₦500 a day for a private company that doesn't qualify as small (or a company limited by guarantee), ₦1,000 a day for a public company, and ₦150 a day for a business name. Second, on top of that, a flat one-off penalty, ₦5,000 for a small company or a business name, ₦10,000 for a larger private company or company limited by guarantee, ₦25,000 for a public company. Run the daily component out even a single year and it dwarfs the one-off amount, which is precisely why a company that has drifted several years behind can end up owing far more than the headline fee figures suggest. It is worth being precise here about a separate wrinkle: CAMA's "small company" threshold, turnover of no more than ₦120,000,000, net assets of no more than ₦60,000,000, directors collectively holding at least 51% of the shares, and no foreign shareholder, is not the same test as the "small company" definition used for tax exemptions under the Nigeria Tax Act 2025, which uses entirely different turnover and asset figures. A company can be small under one test and not the other, so the two should never be assumed interchangeable.

One caveat worth stating plainly: while the daily penalty is genuinely on CAC's official published fee schedule, several compliance firms that handle CAC filings regularly report inconsistent day-to-day enforcement of it in practice, meaning the figure a company is actually asked to pay at the point of filing sometimes falls short of what a strict daily calculation would produce. The one-off penalty, by contrast, is reported far more consistently as actually charged. Anyone budgeting for a genuinely overdue filing should treat the daily-penalty portion of an estimate as an upper bound rather than a certainty, and confirm the actual amount owed directly with the CAC or a chartered secretary before assuming the worst-case number is what will be demanded.

The real risk sits further out than any individual penalty calculation. Under CAMA Section 692(3) and (4), the CAC has the power to strike a company off the register entirely once it has failed to file annual returns for ten consecutive years. This is not a hypothetical power the Commission keeps in reserve. In recent strike-off exercises, the CAC has published lists running into the tens and even hundreds of thousands of company names, sending public notices with a short compliance window, typically around 90 days, for affected companies to file all outstanding returns and confirm their beneficial ownership details before being permanently delisted. A struck-off company loses its legal status outright: it cannot sign contracts, its bank accounts become unusable, and restoring it afterward requires a formal court order, on top of paying every fee and penalty that accrued in the meantime. If a company has gone quiet for a decade or close to it, checking its status on the CAC's public search portal is worth doing sooner rather than later, and definitely before assuming everything is fine simply because no letter has arrived.

None of this replaces professional advice. The figures above come from CAC's own published fee schedule rather than third-party summaries, which is a meaningfully more reliable source, but the schedule itself can still be revised, and this tool has no live connection to CAC's systems. Before paying anything, confirm the current figure directly on the official CAC portal, and for anything beyond a straightforward, recent filing, a chartered secretary or a firm that regularly handles CAC compliance will save far more in avoided mistakes than their fee costs.$body$,
$faq$[
    {"q": "How much does it cost to file CAC annual returns in Nigeria?", "a": "Per CAC's official fee schedule: \u20a63,000 per filing for business names, \u20a65,000 per filing for small and other private companies and companies limited by guarantee, \u20a610,000 per filing for public companies, and \u20a65,000 per filing for incorporated trustees. These are base filing fees and do not include any late penalties owed for prior overdue years."},
    {"q": "What happens if I don't file my CAC annual returns?", "a": "Two penalties apply: a daily default penalty (\u20a6150\u2013\u20a61,000 per day depending on entity type and size) that accrues for every day in default, plus a flat one-off penalty (\u20a65,000\u2013\u20a625,000 depending on entity type). After 10 consecutive years of non-filing, the CAC can strike the company off the register entirely under CAMA Section 692(3)-(4), after which restoration requires a court order."},
    {"q": "Is the CAC late penalty a flat yearly fee?", "a": "No \u2014 this is a common misconception. The official schedule charges a daily default penalty that accrues for every day an entity stays in default, plus a separate flat one-off penalty, not a fee that simply multiplies by the number of years overdue."},
    {"q": "How long do I have before my first annual return is due after registering a company?", "a": "Newly incorporated private companies generally get around 18 months from the date of incorporation before their first annual return is due. Business names have a shorter window, typically expected to file by 30 June of the year following registration."},
    {"q": "What is a 'small company' for CAC purposes?", "a": "Under CAMA Section 394, a small company is a private company with turnover of no more than \u20a6120,000,000, net assets of no more than \u20a660,000,000, directors collectively holding at least 51% of the shares, and no foreign shareholder. This is a different test from the 'small company' definition used for tax exemptions under the Nigeria Tax Act 2025. Small and non-small private companies pay the same base annual returns filing fee, but different late-penalty rates."},
    {"q": "How do I check if my company has already been struck off the CAC register?", "a": "Use the official CAC public search portal at publicsearch.cac.gov.ng to check your company's current registration status using its RC or BN number. This tool cannot access live CAC data, so the portal is the only authoritative source for current status."},
    {"q": "Is the daily CAC penalty actually enforced?", "a": "It is on CAC's official published fee schedule, but several compliance firms report inconsistent day-to-day enforcement in practice \u2014 the amount actually demanded at filing sometimes falls short of a strict daily calculation. Treat the daily-penalty portion of any estimate as an upper bound and confirm the actual amount owed with CAC or a chartered secretary."},
    {"q": "Is this tool giving me official CAC status or legal advice?", "a": "No. This is an educational estimator based on CAC's published fee schedule and CAMA 2020. It cannot verify your company's actual current status \u2014 use the CAC public search portal for that \u2014 and it is not a substitute for advice from a lawyer or chartered secretary."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
