-- seed/nigeria-cac-annual-returns-compliance-checker.sql
-- Run in the Supabase SQL editor once the project is connected.

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-cac-annual-returns-compliance-checker',
  'en',
  'CAC Annual Returns Compliance Checker Nigeria 2026 (Fees & Penalties)',
  'Estimate your CAC annual returns filing fees, late penalties, and strike-off risk for business names, private companies, and NGOs — based on CAMA 2020.',
  'Free CAC annual returns compliance checker for Nigeria. Estimate filing fees, late penalties, and strike-off risk for business names, companies, and NGOs under CAMA 2020.',
  'CAC Annual Returns in Nigeria: Fees, Penalties, and How Strike-Off Actually Works',
$body$Every business registered with Nigeria's Corporate Affairs Commission, whether a business name, a private company, or an incorporated trustee, has one recurring statutory obligation that outlasts the excitement of registration itself: filing annual returns. Unlike tax returns, which report income and go to the Nigeria Revenue Service, annual returns go to the CAC and confirm something narrower but still important, that the entity is still active and that its core records, directors, shareholders, registered address, are accurate. Miss enough of them, and the consequences move from a modest late fee to a genuine risk of losing the company's legal existence entirely.

The mechanics differ by entity type, and getting them mixed up is the single most common source of confusion. Business names, which cover sole proprietorships and partnerships, are expected to file annually by 30 June, with a filing fee of ₦5,000 per year under the CAC's current published schedule. Private companies limited by shares face a different clock: the statutory deadline is technically within 42 days of the company's Annual General Meeting, but in practice, for the many companies with a 31 December financial year-end, that translates to a working deadline around 30 June of the following year, and the filing fee is ₦10,000 per year. A newly incorporated company gets some breathing room before any of this applies, generally around 18 months from incorporation before the first annual return is due, so a company registered late last year is unlikely to be overdue for anything yet even if it feels overdue.

Penalties escalate the longer a filing goes unmade, and the CAC's current framework, under the Companies and Allied Matters Act (CAMA) 2020, treats company size differently. A company that qualifies as a "small company" under CAMA Section 394, meaning turnover of no more than ₦120,000,000, net assets of no more than ₦60,000,000, directors collectively holding at least 51% of the shares, and no foreign shareholder, faces a late penalty of ₦5,000 per year of default. A company that does not meet that definition faces ₦10,000 per year instead. On top of whichever company-level penalty applies, there is a further ₦1,000 per year for each director or officer on record, which means a company with several directors that has drifted several years behind can accumulate a meaningfully larger bill than the headline per-year figure suggests. It is worth being precise here about a separate wrinkle: CAMA's "small company" threshold is not the same test as the "small company" definition used for tax exemptions under the Nigeria Tax Act 2025, which uses different turnover and asset figures entirely. A company can be small under one test and not the other, so the two should never be assumed interchangeable.

There is also, technically, a daily penalty provision written into the Companies Regulations 2021, of up to ₦1,000 per day. As things currently stand, the CAC has suspended enforcement of that daily penalty, so the per-year flat penalties above are what actually gets charged, but the daily provision remains on the books and could in principle be reactivated, which is one more reason to treat "I'll get to it eventually" as a more expensive strategy than it looks. Penalties are also cumulative rather than averaged, so a company that has genuinely gone eight or nine years without filing is not looking at a single lump sum calculated once, it is looking at eight or nine separate years of company-level and director-level penalties stacked on top of eight or nine separate years of filing fees, which is why the total for a long-neglected entity can look shockingly large compared to what a single year's compliance would have cost.

The real risk sits further out. Under CAMA Section 692(3) and (4), the CAC has the power to strike a company off the register entirely once it has failed to file annual returns for ten consecutive years. This is not a hypothetical power the Commission keeps in reserve. In recent strike-off exercises, the CAC has published lists running into the tens and even hundreds of thousands of company names, sending public notices with a short compliance window, typically around 90 days, for affected companies to file all outstanding returns and confirm their beneficial ownership details before being permanently delisted. A struck-off company loses its legal status outright: it cannot sign contracts, its bank accounts become unusable, and restoring it afterward requires a formal court order, on top of paying every fee and penalty that accrued in the meantime. If a company has gone quiet for a decade or close to it, checking its status on the CAC's public search portal is worth doing sooner rather than later, and definitely before assuming everything is fine simply because no letter has arrived.

None of this replaces professional advice, and the fee figures above, while checked against multiple compliance-focused sources, are not pulled from a live CAC data feed, since the Commission does not publish one. Fees are also known to be revised periodically. Before paying anything, confirm the current figure directly on the official CAC portal, and for anything beyond a straightforward, recent filing, a chartered secretary or a firm that regularly handles CAC compliance will save far more in avoided mistakes than their fee costs.$body$,
$faq$[
    {"q": "How much does it cost to file CAC annual returns in Nigeria?", "a": "The CAC's current published schedule charges \u20a65,000 per year for business names and \u20a610,000 per year for private and public companies limited by shares. These are base filing fees per year and do not include any late penalties owed for prior overdue years."},
    {"q": "What happens if I don't file my CAC annual returns?", "a": "Late penalties accrue per year of default \u2014 \u20a65,000/year for a CAMA-defined small company or \u20a610,000/year for other companies, plus \u20a61,000/year per director or officer. After 10 consecutive years of non-filing, the CAC can strike the company off the register entirely under CAMA Section 692(3)-(4), after which restoration requires a court order."},
    {"q": "How long do I have before my first annual return is due after registering a company?", "a": "Newly incorporated private companies generally get around 18 months from the date of incorporation before their first annual return is due. Business names have a shorter window, typically expected to file by 30 June of the year following registration."},
    {"q": "What is a 'small company' for CAC purposes?", "a": "Under CAMA Section 394, a small company is a private company with turnover of no more than \u20a6120,000,000, net assets of no more than \u20a660,000,000, directors collectively holding at least 51% of the shares, and no foreign shareholder. This is a different test from the 'small company' definition used for tax exemptions under the Nigeria Tax Act 2025."},
    {"q": "How do I check if my company has already been struck off the CAC register?", "a": "Use the official CAC public search portal at publicsearch.cac.gov.ng to check your company's current registration status using its RC or BN number. This tool cannot access live CAC data, so the portal is the only authoritative source for current status."},
    {"q": "Is the daily penalty for late CAC filing still being charged?", "a": "The Companies Regulations 2021 provide for a daily penalty of up to \u20a61,000, but the CAC has currently suspended enforcement of this daily penalty. The flat per-year penalties (\u20a65,000\u2013\u20a610,000 depending on company size) are what is currently being charged."},
    {"q": "Do business names and incorporated trustees face the same penalties as companies?", "a": "The exact per-year late penalty for business names and incorporated trustees is less consistently documented than for companies. This tool applies a conservative estimate for these entity types \u2014 always confirm the exact current figure on the CAC portal before paying."},
    {"q": "Is this tool giving me official CAC status or legal advice?", "a": "No. This is an educational estimator based on publicly available information about CAMA 2020 requirements. It cannot verify your company's actual current status \u2014 use the CAC public search portal for that \u2014 and it is not a substitute for advice from a lawyer or chartered secretary."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
