insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-crop-yield-estimator',
  'en',
  'Nigeria Crop Yield Calculator — Estimate Harvest by State & Crop (Maize, Cassava, Rice & More)',
  'Estimate expected crop yield and harvest tonnage for your farm in Nigeria based on crop type, state, land size, and season.',
  'Free Nigeria crop yield calculator. Estimate maize, cassava, rice, yam, and other crop harvests by state, land size, and season using NBS, USDA, and FAO data.',
  'Nigeria Crop Yield Calculator: What Can You Really Expect to Harvest?',
$body$Every farmer, agribusiness planner, and input supplier in Nigeria eventually asks the same question before a planting season begins: how much can this piece of land realistically produce? A crop yield estimator gives you a fast, data-grounded starting point for that question, using historical averages for your crop and state rather than a guess, so you can plan input purchases, expected income, and storage or logistics needs before a single seed goes into the ground.

The foundation of any yield estimate in Nigeria is the national and state-level average, expressed in tons per hectare. These figures are compiled and published annually through the Agricultural Performance Survey, a joint exercise coordinated by the Federal Ministry of Agriculture and Rural Development, or FMARD, together with the National Bureau of Statistics, or NBS, and the National Agricultural Extension and Research Liaison Services, known as NAERLS, based at Ahmadu Bello University in Zaria. International datasets from the United States Department of Agriculture's Foreign Agricultural Service, or USDA FAS, and the Food and Agriculture Organization, or FAO, are also used to cross-check and fill gaps where subnational Nigerian data is incomplete for a given crop or year. Because these surveys are revised and republished periodically, any yield calculator, including this one, should be treated as a snapshot that needs occasional refreshing rather than a fixed, permanent figure.

Yield in Nigeria varies enormously by geography, and this is the single biggest reason a national average alone is not good enough for planning purposes. Maize grown in Kaduna or Benue, in the North West and North Central zones respectively, regularly outperforms the national average because of better rainfall distribution during the growing season and higher fertilizer adoption among commercial-scale farmers there. Cassava tells almost the opposite story: yields in Kogi, Benue, and much of the South West and South East tend to exceed those in the far north, since cassava favors the humid, longer growing conditions found closer to the coast. Rice shows a similar split, with irrigated schemes in Kebbi and lowland or swamp rice in Ebonyi consistently producing more per hectare than rain-fed upland rice grown elsewhere. This is why a state-level, or at minimum a zonal, estimate is always more useful than a single blanket national number, and why selecting your specific state matters more for accuracy than any other single input in a tool like this.

Beyond location, three practical factors shift a farm's actual output away from the historical average, and each is easy to reason about even without formal agronomic training. The first is season: major or wet-season planting, which relies on the main rains, produces very differently from minor or dry-season planting, and irrigated production, where water is controlled rather than rain-dependent, typically performs best of all. The second is management level, meaning how intensively a farmer uses purchased inputs like fertilizer, improved seed, and crop protection chemicals; low-input or subsistence farming, average smallholder practice, and improved high-input management can easily separate low and high performers by 30 to 40 percent on the same land. The third is the set of local, unpredictable factors, rainfall timing, pest and disease pressure, and soil fertility, that no calculator can fully account for, which is exactly why any credible estimate is presented as a range rather than a single fixed number.

Understanding your likely yield matters most when it feeds into a broader financial picture. Once expected production in tons is known, it can be multiplied by a sample market price to produce a rough revenue estimate for planning purposes, though farm-gate prices for crops like maize, cassava, rice, and cocoa fluctuate significantly by season, by buyer, and by location, so any revenue figure from a calculator should be treated as directional rather than a quote. For farmers seeking a firmer number closer to harvest time, checking current local market prices through a state ministry of agriculture office or a produce buyers' association is a better source than any historical average.

It is worth being direct about what a tool like this cannot do. It cannot diagnose a specific field's soil condition, recommend a fertilizer program, identify a pest or disease outbreak, or replace an agronomist's assessment of a particular farm. Nigeria's extension system exists precisely to fill that gap: each state runs an Agricultural Development Programme, or ADP, typically staffed with extension officers who can visit a farm, assess local conditions, and give recommendations specific to that soil, that crop variety, and that season. NAERLS, together with FMARD, coordinates research-to-farmer knowledge transfer at a national level and is a useful next step for anyone who wants guidance beyond a general estimate. Farmers, cooperative managers, and input dealers should treat this calculator as a starting point for planning conversations with those services, not as a substitute for them, and should expect real results to differ from any historical average based on the actual conditions of their specific field in a given year.$body$,
$faq$[
  {"q": "How accurate is a crop yield calculator for Nigeria?", "a": "It gives a directional estimate based on historical state and national averages from NBS, USDA FAS, and FAO data — actual yields on any specific farm can vary widely due to weather, soil, seed variety, and management practices."},
  {"q": "What is the average maize yield per hectare in Nigeria?", "a": "The national average is roughly 1.8 tons per hectare, though well-managed farms in Kaduna or Benue with good rainfall and fertilizer use often exceed 2.5 tons per hectare."},
  {"q": "How much cassava can I get from one hectare in Nigeria?", "a": "National averages run around 8–12 tons per hectare, with well-managed farms in Kogi, Benue, and parts of the South West and South East regularly reaching 12–14 tons or more."},
  {"q": "Does irrigation really increase crop yield significantly?", "a": "Yes — irrigated production removes dependence on rainfall timing and typically outperforms both major (wet) and minor (dry) season rain-fed farming, especially for rice."},
  {"q": "Where can I get farm-specific advice instead of a general estimate?", "a": "Contact your state's Agricultural Development Programme (ADP) or NAERLS, which coordinates extension services with FMARD, for guidance based on your actual soil, seed variety, and local conditions."},
  {"q": "Why does my state's yield differ so much from the national average?", "a": "Yield varies by agro-ecological zone — for example, cassava favors the humid South while maize often performs better with the rainfall patterns of the North West and North Central zones."},
  {"q": "How is expected farm revenue calculated from projected yield?", "a": "Projected tons of production are multiplied by a sample market price, but this is only directional since farm-gate prices fluctuate by season, buyer, and location."},
  {"q": "What crops can I estimate yield for in this calculator?", "a": "Common Nigerian staples including maize, cassava, rice, yam, sorghum, millet, groundnut, soybean, cowpea, oil palm, and cocoa, plus a manual entry option for other crops."}
]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
