-- seed/nigeria-scholarship-eligibility-matcher.sql
-- Run in the Supabase SQL editor once the project is connected.
-- Uses dollar-quoting ($body$...$body$ and $faq$...$faq$) throughout so
-- apostrophes in the copy never need manual escaping.

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-scholarship-eligibility-matcher',
  'en',
  'Scholarship Eligibility Matcher Nigeria 2026 — Federal, State & Corporate Awards',
  'Answer a few questions about your state, level of study, and academic profile to instantly see which Nigerian federal, state, and corporate scholarships or bursaries you may qualify for.',
  'Free Nigeria scholarship matcher for 2026. Enter your state of origin, course, and CGPA to see which federal, state, and corporate scholarships or bursaries you are likely eligible for, with links to apply.',
  'How to Find a Scholarship You Actually Qualify For in Nigeria',
$body$Every admission season, thousands of Nigerian students spend hours scrolling through scattered scholarship lists, only to discover halfway through a long application form that the award is restricted to a state they were not born in, or a course they are not studying. The problem is not that scholarships and bursaries are scarce — Nigeria actually runs dozens of them every year across the Federal Government, all 36 state governments plus the FCT, and a long list of corporate sponsors in oil and gas, telecoms, and banking. The problem is that eligibility criteria are scattered across state gazettes, ministry circulars, and one-off newspaper announcements, so most students only find out they were never eligible after they have already spent time and, in some cases, money preparing an application. A scholarship eligibility matcher solves that by asking for a profile once and checking it against every scheme's published criteria at the same time.

The single biggest filter in the Nigerian scholarship landscape is indigeneship. Most state bursary boards — from the Lagos State Bursary Award to schemes run by Delta, Rivers, Kano, Kaduna, Enugu, Anambra, Ogun, Ekiti, Osun, and Akwa Ibom State — are only open to indigenes of that specific state, verified through a Local Government Area (LGA) of origin certificate signed by the LGA chairman or secretary. This is not optional paperwork; state scholarship boards routinely reject applications at the verification stage when a certificate is expired, incomplete, or issued by the wrong LGA office. A handful of federal schemes work differently: the Niger Delta Development Commission (NDDC) scholarship, for instance, is federal in funding but still restricted to indigenes of its nine mandate states — Abia, Akwa Ibom, Bayelsa, Cross River, Delta, Edo, Imo, Ondo, and Rivers. Knowing this distinction upfront saves an applicant from investing time in a scheme they were never eligible for on residency grounds alone.

The second major filter is level of study, and it trips up more applicants than it should. Federal Government National Merit Scholarships, administered by the Federal Scholarship Board (FSB) under the Federal Ministry of Education, are typically aimed at undergraduates already in 200 level or above at a federal or state public institution — first-year students and private university students are usually excluded outright. Postgraduate-specific awards, whether from the FSB, the Petroleum Technology Development Fund (PTDF), or individual state scholarship boards, run entirely separate application cycles with their own cut-off marks, so an undergraduate scanning a postgraduate scheme's requirements (or vice versa) is checking the wrong list from the start.

Academic thresholds form the third layer. Most merit-based federal and corporate schemes set a minimum CGPA, commonly somewhere around 3.0 to 3.5 on a 5.0 scale, along with a minimum number of O-Level credits — typically five, always including English Language and Mathematics — from WAEC or NECO in no more than two sittings. Corporate-sponsored schemes such as the MTN Foundation Scholarship and the NNPC/Total National Merit Scholarship Scheme tend to weight STEM and engineering courses more heavily, reflecting the sponsor's own recruitment interests, while state bursaries are often broader on course eligibility but stricter on the indigeneship requirement described above. A first-year undergraduate has no CGPA history yet, which is exactly why CGPA-gated awards specify 200 level and above — there is nothing to evaluate before that point.

A smaller set of criteria affects a narrower group of applicants but matters a great deal when it applies. Federal education policy reserves a share of support slots — commonly cited around five percent — for students with disabilities, and several federal and state programmes apply this priority explicitly rather than leaving it to informal discretion. Institution type is another filter that is easy to miss: a number of federal merit schemes are restricted to federal or state public universities, polytechnics, and colleges of education, which quietly excludes private university students even when their grades would otherwise qualify. Corporate host-community scholarships, run by companies such as Chevron, Shell/SPDC, and other oil and gas operators, go a step further and restrict eligibility to residents of the specific communities where that company operates — Chevron's scheme, for example, has historically focused on Delta, Ondo, and Lagos host communities, while SPDC's has centered on Rivers, Bayelsa, Delta, Imo, Abia, and Akwa Ibom.

Once a student's profile — state, level, field of study, CGPA, O-Level result, institution type, and any disability status — is checked against this full set of criteria at once, the useful output is not a single yes-or-no answer but a ranked list: schemes where every hard requirement is met sit at the top as high matches, schemes where the core eligibility (state and level) fits but one or two softer criteria such as CGPA or field of study fall short appear as possible matches worth watching for the next cycle, and schemes that are structurally closed to the applicant (wrong state, wrong level) are filtered out entirely rather than wasting anyone's time. This mirrors how a careful applicant would triage a spreadsheet of scholarships manually, just faster and without the risk of missing a scheme buried in a state gazette PDF.

None of this replaces verifying the details directly with the awarding body before applying. Scholarship amounts, application windows, and even eligibility rules shift from one admission cycle to the next — a state bursary board can widen or narrow its indigeneship verification process, and a corporate scheme can change its priority field of study with little notice. The Federal Ministry of Education's portal, each State Scholarship and Bursary Board, and each scheme's own official page remain the authoritative source once a shortlist of plausible matches has been narrowed down. What a matcher tool like this genuinely saves is the first, most time-consuming step: working out which of the dozens of schemes running in a given year are even worth a closer look for a specific student's actual state, level, course, and grades.$body$,
$faq$[
    {"q": "Is this scholarship matcher free to use?", "a": "Yes. There is no sign-up. Fill in your state, level of study, and academic details, and the tool instantly shows federal, state, and corporate schemes you are likely to qualify for."},
    {"q": "Does this tool submit my scholarship application for me?", "a": "No. It only checks your profile against published eligibility criteria and links you to each scheme's official portal. You still need to apply directly with that scheme, including your LGA indigene certificate, transcripts, and admission letter."},
    {"q": "Why do I need an LGA of origin certificate for state scholarships?", "a": "Almost every state bursary board -- Lagos, Delta, Rivers, and others -- verifies applicants using a Local Government Area indigene certificate signed by the LGA chairman or secretary. Without one, most state boards will reject an application at the verification stage regardless of your grades."},
    {"q": "I'm a first-year undergraduate. Why do most schemes show me as ineligible?", "a": "Most CGPA-based federal and corporate scholarships require you to be at 200 level or above, since a first-year student has no CGPA history yet to evaluate. Some schemes do accept fresh admissions based on JAMB or O-Level results instead -- check the 'Possible' matches for these."},
    {"q": "Does my institution type matter?", "a": "Yes. Several federal merit scholarships, including the National Merit Award and MTN Foundation Scholarship, are restricted to students in federal or state public institutions and exclude private university students, even with a strong CGPA."},
    {"q": "What if I have a disability?", "a": "Federal education policy reserves a share of scholarship and support slots, commonly cited around 5%, for students with disabilities. Ticking the disability option in this tool surfaces schemes that apply this priority explicitly."},
    {"q": "How often is the scholarship data in this tool updated?", "a": "The list is reviewed and refreshed periodically from official sources such as education.gov.ng and individual state scholarship board portals. Because amounts and application windows change every cycle, always confirm current details on the scheme's own site before applying."},
    {"q": "Can NYSC corps members or Nigerians studying abroad use this tool?", "a": "This version focuses on federal, state, and corporate schemes for students in Nigerian institutions. If you are studying overseas, check the PTDF Overseas Postgraduate Scholarship and your State Scholarship Board, both of which sometimes run separate overseas tracks."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
