-- seed/nigeria-cac-registration-calculator.sql
-- Run in the Supabase SQL editor once the project is connected.
-- Figures corrected against CAC's official downloadable fee schedule
-- (cac.gov.ng/api/download-fees) — the original version of this article
-- relied on third-party guides that disagreed with the official schedule
-- on several line items, including the private company base registration
-- fee (₦40,000 quoted originally vs. ₦10,000 on the actual schedule).

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'nigeria-cac-registration-calculator',
  'en',
  'CAC Registration Cost Calculator Nigeria 2026 (Business Name vs Ltd)',
  'Estimate CAC registration costs for a business name, private company, company limited by guarantee, or NGO in Nigeria, based on the official CAC fee schedule.',
  'Free CAC registration cost calculator for Nigeria, based on the official CAC fee schedule. Compare business name vs private limited company fees, timelines, and requirements for 2026.',
  'How Much Does CAC Registration Actually Cost in Nigeria in 2026?',
$body$Ask five different sources how much it costs to register a business with Nigeria's Corporate Affairs Commission, and there is a real chance you get five different numbers. Some quote ₦10,500 for a business name. Others say ₦21,000. Some put a private limited company's base registration at ₦10,000, others at ₦40,000, a four-fold difference for what should be a fixed government fee. Checked directly against CAC's own published fee schedule rather than third-party summaries, the lower end of that range turns out to be the correct one, and it's worth understanding why the gap exists at all: CAC's fee schedule has genuinely been revised more than once in the past two years, and different guides and agencies have updated to different degrees, leaving a lot of confidently wrong information in circulation. The figures below come from the CAC's own downloadable fee schedule.

A business name, the registration route for sole proprietorships and partnerships, costs ₦500 to reserve the name (₦5,000 if it uses a restricted word or company-style suffix) plus ₦10,000 to register, for a total of ₦10,500 in official CAC fees before any portal transaction charge. A private company limited by shares, the standard structure for a business planning to scale or bring in outside shareholders, costs ₦500 for name reservation plus ₦10,000 in registration fees for issued share capital up to ₦1,000,000, whether or not the company qualifies as a CAMA "small company," the registration fee tier is identical either way. Above ₦1,000,000 and up to ₦500,000,000 of share capital, CAC charges ₦5,000 for every ₦1,000,000 or part thereof; above ₦500,000,000, that rises to ₦7,500 per ₦1,000,000. Public companies pay roughly double these per-million rates. On top of the CAC fee sits a separate, federal stamp duty charged by FIRS, not CAC, at approximately 0.75% of share capital, which adds roughly ₦7,500 on a standard ₦1,000,000 registration, bringing the realistic all-in total for a typical ₦1,000,000 private company to around ₦18,000.

The choice between a business name and a private limited company is not primarily a pricing decision, even though the private company costs somewhat more upfront. It is a liability and growth decision. A business name offers no separation between you and your business: if the business owes money it cannot pay, creditors can, in principle, pursue your personal assets. A private limited company creates a distinct legal person, and shareholders generally risk only what they invested in shares. If you plan to bring on investors, apply for meaningful business financing, or simply want a firewall between business risk and personal assets, the additional cost of incorporation tends to look small next to what it protects. If you are testing an idea, working as a freelancer, or running a small local trade with no near-term plan to raise capital, a business name gets you legally recognized, able to open a corporate account, and able to sign contracts, at a fraction of the cost and paperwork.

Two other structures round out the common options. A Company Limited by Guarantee, at ₦5,000 name reservation and ₦20,000 to incorporate, suits organizations that need corporate legal status but have no shareholders and no share capital, professional bodies, think tanks, and similar non-profit-adjacent entities, though it requires Attorney General of the Federation approval before the CAC will incorporate it, which realistically adds weeks to the timeline regardless of how quickly the CAC itself processes the filing. Incorporated Trustees is the structure NGOs, churches, mosques, and community associations use, costing ₦5,000 to reserve the name and ₦35,000 to register, and it carries its own procedural weight beyond the fee: a mandatory 28-day newspaper publication and public objection period before registration completes, with newspaper costs themselves typically adding another ₦20,000 to ₦30,000 on top of CAC's own fees.

Whichever structure fits, the process itself now runs almost entirely online through the CAC's portal: search and reserve a name, which stays held for 60 days once approved, complete the relevant registration form with entity and ownership details, upload supporting documents, pay the applicable fees, and download the certificate once approved. Since 2026, incorporation also requires disclosing Persons with Significant Control, anyone owning or controlling more than 25% of the company, at the point of registration rather than as a later filing. Most delays come down to avoidable errors: blurry or black-and-white ID scans, a proposed name too close to an existing registration, or incomplete director and shareholder details. Budgeting realistically also means accounting for what falls outside CAC's own fee schedule entirely: opening a corporate bank account typically requires an initial deposit in the ₦10,000–₦20,000 range, and anyone hiring a lawyer or accredited agent rather than self-filing should expect professional fees on top of the official amounts, which vary widely by firm and complexity.

None of the figures here should be treated as final. Fee schedules and processing charges change with enough regularity that the single most reliable step in this entire process is confirming the live cost on the official CAC portal in the same session you intend to pay.$body$,
$faq$[
    {"q": "How much does it cost to register a business name with CAC in Nigeria?", "a": "Per CAC's official fee schedule: \u20a6500 for name reservation (\u20a65,000 if the name uses a restricted word) plus \u20a610,000 for registration, for a total of \u20a610,500 in official fees. This excludes portal transaction fees and any agent charges."},
    {"q": "How much does it cost to register a private limited company in Nigeria?", "a": "For issued share capital up to \u20a61,000,000: \u20a6500 name reservation plus \u20a610,000 CAC registration fee, plus roughly \u20a67,500 FIRS stamp duty (approximately 0.75% of share capital) \u2014 around \u20a618,000 all in. Above \u20a61,000,000 and up to \u20a6500,000,000, CAC charges an additional \u20a65,000 per \u20a61,000,000 or part thereof."},
    {"q": "Why do different websites quote such different CAC registration fees?", "a": "CAC's fee schedule has been revised more than once in recent years, and different guides have updated to different degrees, leaving inconsistent figures in circulation. Some sources quote a private company's base registration fee as \u20a640,000 when the current official schedule sets it at \u20a610,000 for issued share capital up to \u20a61,000,000. Always confirm the current fee on the CAC portal before paying."},
    {"q": "Should I register a business name or a limited company?", "a": "A business name is cheaper and faster but offers no separation between you and the business \u2014 you are personally liable for its debts. A private limited company costs somewhat more upfront but limits shareholders' liability to what they invested, and is generally necessary if you plan to raise investment or bring on multiple owners."},
    {"q": "What is the minimum share capital for a private company in Nigeria?", "a": "CAMA 2020 sets the minimum issued share capital for a private company at \u20a6100,000, though \u20a61,000,000 is the practical figure most startups use, partly because CAC's registration fee tiers are structured around \u20a61,000,000 increments."},
    {"q": "How long does CAC registration take?", "a": "A business name typically takes 1\u20137 working days, often same-day to 72 hours online. A private limited company typically takes 3\u201314 working days. Incorporated Trustees (NGOs) take significantly longer, 6\u20138 weeks, due to a mandatory 28-day newspaper publication and objection period."},
    {"q": "Does CAC charge an additional AI service fee?", "a": "Some 2026 news coverage reported an additional CAC processing charge tied to AI-assisted platform services, but this does not appear on CAC's current official downloadable fee schedule, so it is not included in the totals above. Budget a small buffer for it just in case it applies at the point of payment."},
    {"q": "Is this calculator giving me the official CAC price?", "a": "The figures are drawn directly from CAC's own published fee schedule rather than third-party summaries, which is a meaningfully more reliable source than most guides in circulation \u2014 but this tool has no live connection to CAC's systems, and fee schedules can be revised. Always verify the exact current cost on the official CAC portal (pre.cac.gov.ng) before paying."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
