-- seed/startup-cost-break-even-analyzer.sql
-- Run in the Supabase SQL editor once the project is connected.

insert into tool_translations (
  tool_slug, locale, title, description, meta_description,
  article_title, article_body, faq, is_translated
) values (
  'startup-cost-break-even-analyzer',
  'en',
  'Nigeria Startup Cost & Break-Even Calculator: POS Agent, Shop & Small Business',
  'Work out exactly how much you need to start a POS agent business, a provision shop, or a small service business in Nigeria, and how long it will take to break even.',
  'Free Nigeria startup cost and break-even calculator for POS agents, provision shops, and small service businesses. Get realistic 2026 cost ranges, break-even revenue, and months to recover your investment.',
  'How Much Does It Really Cost to Start a Small Business in Nigeria?',
$body$Every "start a business with ₦100,000" article in Nigeria tells half the story. It lists the terminal, the shop rent, or the tools — then quietly leaves out the number that actually determines whether the business survives its first three months: working capital. A POS agent with a brand-new terminal and an empty float cannot serve a single customer. A shop with beautiful shelving and no stock is just an empty room. The setup cost gets you open. The working capital keeps you open. Any honest startup budget has to count both, and then go one step further and ask when the business actually starts making more than it spends.

For a POS agency, the setup side is the cheap part. A terminal is often free or subsidized by the provider, sometimes with a caution fee in the tens of thousands of naira; a small table, umbrella or kiosk setup with signage typically adds another twenty to thirty thousand naira; and registering a business name with the Corporate Affairs Commission (CAC) currently runs somewhere in the ₦10,000 to ₦20,000 range in CAC's own filing fee, with a realistic ₦15,000 to ₦35,000 all-in once you account for the separate name reservation fee and any cybercafé or agent assistance — CAC updates this schedule periodically, so it is always worth checking the current figure on the official portal, portal.cac.gov.ng, before paying. The real number that makes or breaks a POS business is the float: the cash sitting in your account and in hand to cover withdrawals and transfers. Running out of float mid-transaction does not just lose you a customer, it can lose you a location's worth of trust. A safe starting float generally runs ₦50,000 to ₦250,000 or more, scaling up sharply in busy Lagos locations compared to quieter towns. One regulatory detail worth knowing before choosing a provider: from 1 April 2026, the Central Bank of Nigeria's agent banking guidelines require every POS agent to operate with a single principal — one bank, mobile money operator, microfinance bank, or licensed super-agent — rather than running multiple providers' terminals side by side as many agents previously did.

A provision or retail shop flips that ratio. Shelving, furniture, and signage are a one-time cost, typically eighty to a hundred and fifty thousand naira for a modest setup, but the money that actually determines how the shop performs is the stock sitting on those shelves. A small neighbourhood shop can realistically open with a few hundred thousand naira in inventory, while a shop aiming to stock a fuller range of fast-moving consumer goods often needs seven figures. Rent adds a second wrinkle: Nigerian shop landlords very commonly ask for a year upfront rather than month to month, so a rent figure that looks manageable annually can still demand a large lump sum at the point you sign the lease — worth converting to a monthly equivalent when comparing it against your expected monthly profit, which is exactly what a break-even calculation forces you to do.

Small service businesses — a hair or barbing salon, a phone or appliance repair stand, a food vendor — sit in between. The startup cost leans toward tools and equipment rather than a large stock float: clippers and styling equipment for a salon, a diagnostic kit for a repair business, a cooker and utensils for a food stall. Ongoing costs then lean heavily on consumables and materials that get used up with every customer served, which is why the monthly cost side of the picture matters as much as the opening one.

Once the costs are laid out, break-even analysis turns them into a single, comparable number. The formula is simple: break-even revenue equals your monthly fixed costs divided by your gross margin — the share of every naira of revenue left over after direct costs like stock, materials, or transaction costs are paid. A shop with ₦40,000 in monthly fixed costs and a 22% margin, a blended figure typical of Nigerian FMCG and household-goods retail, needs to bring in roughly ₦182,000 in monthly sales just to break even, before a single naira of profit. A POS agent, whose margin on the fee income itself is much higher since there is no physical stock to buy, breaks even at a much lower revenue figure relative to fixed costs — but has to actually generate that many transactions, which depends entirely on footfall and location.

The other question every new business owner asks — how long until I get my money back — is really just startup cost divided by monthly profit, projected under a few different assumptions rather than one. A single "expected revenue" number invites false confidence; running the same math at a pessimistic, realistic, and optimistic revenue level shows the actual range of outcomes, and whether the business is resilient to a bad month or entirely dependent on a good one.

Tax is a smaller consideration at this scale than most first-time business owners assume, but it is worth knowing the shape of it. Under the Nigeria Tax Act 2025, effective 1 January 2026, an unincorporated sole proprietor or business name is taxed as an individual under Personal Income Tax bands that start at zero on the first ₦800,000 of annual chargeable income — a threshold most POS agents, shop owners, and service providers starting out will sit comfortably under or just above. An incorporated company with turnover at or below ₦100,000,000 and fixed assets under ₦250,000,000 qualifies as a small company and pays 0% Companies Income Tax, though it still must file annual returns with the Corporate Affairs Commission. VAT registration is only mandatory above ₦50,000,000 in annual turnover, well beyond the range most of these businesses operate in during their first year. None of this replaces proper advice from a tax professional or the Nigeria Revenue Service, but it does mean the tax question rarely changes the viability decision at the startup stage — the real work is getting the setup cost, the working capital, and the break-even math right first.$body$,
$faq$[
    {"q": "How much does it really cost to start a POS business in Nigeria?", "a": "Setup items (terminal, kiosk/table, signage, CAC registration) typically run ₦50,000 to ₦100,000, but the float -- the cash you need on hand to serve customers -- usually adds ₦50,000 to ₦250,000 or more, higher in busy Lagos locations. Total realistic budget: roughly ₦100,000 to ₦350,000."},
    {"q": "How much stock do I need to open a small provision shop?", "a": "A small neighbourhood shop can realistically open with ₦100,000 to ₦300,000 in stock, while a shop aiming for a fuller product range often needs ₦500,000 to ₦1,000,000 or more. Shelving, furniture, and signage are usually a smaller one-time cost on top of that."},
    {"q": "What is break-even revenue and how is it calculated?", "a": "Break-even revenue is the monthly sales figure at which you cover all your costs exactly, with no profit and no loss. It's calculated as Monthly Fixed Costs divided by Gross Margin (the share of each naira of revenue left after direct costs like stock or materials are paid)."},
    {"q": "How much does CAC business name registration cost in 2026?", "a": "CAC's own filing fee for a business name currently runs roughly ₦10,000 to ₦20,000, plus a separate name reservation fee. A realistic all-in budget, including any cybercafé or agent assistance, is ₦15,000 to ₦35,000. CAC updates its fee schedule periodically, so confirm the current figure on portal.cac.gov.ng before paying."},
    {"q": "Do I need to register my small business with the CAC before starting?", "a": "It's not always legally mandatory to start trading, but CAC registration is required to open a business bank account, work with most suppliers on credit terms, or bid for larger contracts, and it's generally treated as standard practice as a business grows past its earliest, smallest stage."},
    {"q": "Will I need to pay tax on a small POS, shop, or service business?", "a": "Under the Nigeria Tax Act 2025 (effective 1 January 2026), an unregistered or business-name sole proprietor is taxed as an individual, with the first ₦800,000 of annual chargeable income tax-free. Most businesses at this startup scale fall at or near that threshold in their first year, though it's worth tracking income and expenses from day one regardless."},
    {"q": "Is one POS provider enough, or should I run multiple terminals?", "a": "From 1 April 2026, the Central Bank of Nigeria's agent banking guidelines require every POS agent to operate with a single principal -- one bank, mobile money operator, microfinance bank, or licensed super-agent -- rather than running terminals from multiple providers side by side."}
  ]$faq$::jsonb,
  true
)
on conflict (tool_slug, locale) do update set
  title = excluded.title,
  description = excluded.description,
  meta_description = excluded.meta_description,
  article_title = excluded.article_title,
  article_body = excluded.article_body,
  faq = excluded.faq,
  is_translated = excluded.is_translated;
