export type ToolSchema =
  | 'calculator'
  | 'converter'
  | 'generator'
  | 'checker'
  | 'estimator'
  | 'planner'

export type Tool = {
  slug: string
  category: string
  schema: ToolSchema
  featured: boolean
  countries: string[]
  relatedTools: string[]
  relatedArticles: string[]
  hasCountryVariants: boolean
  requiresApi: boolean
  launchDate: string
}

export const TOOLS: Tool[] = [

  // ─── FINANCE ──────────────────────────────────────────────
  {
    slug: 'salary-calculator',
    category: 'finance',
    schema: 'calculator',
    featured: true,
    countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
    relatedTools: ['loan-emi-calculator', 'gratuity-calculator', 'savings-goal-calculator'],
    relatedArticles: ['how-to-calculate-salary-uae', 'salary-guide-gulf-2024'],
    hasCountryVariants: true,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
{
  slug: 'loan-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
  relatedTools: ['salary-calculator', 'saudi-loan-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: true,
  requiresApi: false,
  launchDate: '2025-01-01',
},
  {
    slug: 'compound-interest-calculator',
    category: 'finance',
    schema: 'calculator',
    featured: false,
    countries: ['uae', 'saudi', 'qatar', 'kuwait'],
    relatedTools: ['savings-goal-calculator', 'retirement-planner'],
    relatedArticles: ['power-of-compound-interest'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
{
  slug: 'savings-goal-calculator',
  category: 'finance',
  schema: 'planner',
  featured: false,
  countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman'],
  relatedTools: ['compound-interest-calculator', 'salary-calculator'],
  relatedArticles: ['how-to-save-money-gulf'],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-salary-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'uae-gratuity-calculator', 'vat-calculator'],
  relatedArticles: [],
  hasCountryVariants: true,          // Dubai, Abu Dhabi variants share this page
  requiresApi: false,
  launchDate: '2025-06-01',
},
{
  slug: 'dubai-salary-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae'],
  relatedTools: ['uae-salary-calculator', 'uae-gratuity-calculator', 'vat-calculator', 'salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-06-01',
},
{
  slug: 'saudi-salary-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['saudi'],
  relatedTools: ['saudi-loan-calculator', 'salary-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'egypt-salary-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['egypt'],
  relatedTools: ['salary-calculator', 'saudi-salary-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'saudi-vacation-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['saudi', 'uae', 'qatar', 'kuwait', 'bahrain'],
  relatedTools: ['salary-calculator', 'end-of-service-calculator', 'gosi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-car-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'saudi-loan-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'qatar-salary-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['qatar'],
  relatedTools: ['saudi-salary-calculator', 'salary-calculator', 'egypt-salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-loan-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae', 'dubai'],
  relatedTools: ['salary-calculator', 'saudi-loan-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-loan-eligibility-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae', 'dubai'],
  relatedTools: ['uae-loan-emi-calculator', 'salary-calculator', 'saudi-loan-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'gcc-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae', 'saudi', 'qatar', 'kuwait', 'oman', 'bahrain', 'egypt'],
  relatedTools: ['salary-calculator', 'saudi-loan-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'kuwait-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['kuwait'],
  relatedTools: ['gcc-emi-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'top-up-loan-calculator-uae',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: [
    'loan-emi-calculator',
    'salary-calculator',
    'profit-margin-calculator',
  ],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'car-loan-calculator-uae',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
  relatedTools: [
    'loan-emi-calculator',
    'top-up-loan-calculator-uae',
    'salary-calculator',
    'profit-margin-calculator',
  ],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'oman-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['oman'],
  relatedTools: ['loan-emi-calculator', 'salary-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: true,          // "oman-loan-calculator" is a variant
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'oman-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['oman'],
  relatedTools: ['oman-emi-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: true,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'car-loan-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'car-loan-eligibility-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['car-loan-emi-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'credit-card-emi-calculator-uae',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: [
    'loan-emi-calculator',
    'salary-calculator',
    'profit-margin-calculator',
    'vat-calculator-uae',
  ],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-end-of-service-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'uae-gratuity-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-final-settlement-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-end-of-service-calculator', 'salary-calculator', 'uae-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'qatar-gratuity-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['qatar'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'kuwait-gratuity-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['kuwait'],
  relatedTools: ['qatar-gratuity-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'oman-gratuity-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['oman'],
  relatedTools: ['qatar-gratuity-calculator', 'kuwait-gratuity-calculator', 'salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'bahrain-gratuity-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['bahrain'],
  relatedTools: ['salary-calculator', 'uae-gratuity-calculator', 'end-of-service-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-indemnity-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'bahrain-gratuity-calculator', 'uae-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-leave-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-indemnity-calculator', 'salary-calculator', 'bahrain-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'adcb-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'mortgage-calculator-dubai'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'emirates-nbd-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['adcb-loan-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
   slug: 'hsbc-loan-calculator-uae',
   category: 'finance',
   schema: 'calculator',
   featured: false,
   countries: ['uae'],
   relatedTools: ['adcb-loan-calculator', 'emirates-nbd-loan-calculator', 'salary-calculator'],
   relatedArticles: [],
   hasCountryVariants: false,
   requiresApi: false,
   launchDate: '2025-01-01',
 }, 
{
  slug: 'qatar-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['qatar'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'saudi-loan-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-personal-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'qatar-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-loan-repayment-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-personal-loan-calculator', 'salary-calculator', 'qatar-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-loan-amortization-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-early-settlement-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-loan-amortization-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'oman-salary-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['oman'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-leave-pay-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'uae-gratuity-calculator', 'oman-salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-holiday-pay-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-leave-pay-calculator', 'salary-calculator', 'uae-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-credit-card-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: [
    'loan-emi-calculator',
    'salary-calculator',
    'uae-vat-calculator',
    'profit-margin-calculator',
  ],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'adcb-emi-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: [
    'uae-credit-card-emi-calculator',
    'loan-emi-calculator',
    'salary-calculator',
    'uae-vat-calculator',
  ],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'mashreq-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'deem-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['mashreq-loan-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'dbr-calculator-uae',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['mashreq-loan-calculator', 'deem-loan-calculator', 'salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'flat-interest-rate-calculator-uae',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
 
// ─── MORTGAGE  ─────────────────────────────────────────
{
  slug: 'adcb-mortgage-calculator-dubai',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-free-zone-gratuity-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-mortgage-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'dubai-mortgage-calculator-non-residents',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae'],
  relatedTools: ['uae-mortgage-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'home-loan-calculator-dubai',
  category: 'finance',
  schema: 'calculator',
  featured: true,
  countries: ['uae'],
  relatedTools: ['uae-mortgage-calculator', 'dubai-mortgage-calculator-non-residents', 'salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'fab-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'loan-emi-calculator', 'mortgage-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'rakbank-loan-calculator',
  category: 'finance',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['fab-loan-calculator', 'salary-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},

  
// ─── HR & PAYROLL ─────────────────────────────────────────
{
  slug: 'uae-gratuity-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'uae-pension-calculator', 'end-of-service-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-domestic-worker-gratuity-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-gratuity-calculator', 'salary-calculator', 'uae-leave-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'saudi-annual-leave-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['saudi'],
  relatedTools: ['salary-calculator', 'saudi-loan-calculator', 'gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'qatar-overtime-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['qatar'],
  relatedTools: ['salary-calculator', 'saudi-annual-leave-calculator', 'gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},

  {
    slug: 'gratuity-calculator',
    category: 'hr-payroll',
    schema: 'calculator',
    featured: true,
    countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman'],
    relatedTools: ['salary-calculator', 'notice-period-calculator', 'leave-encashment-calculator'],
    relatedArticles: ['uae-gratuity-law-explained', 'end-of-service-guide-gulf'],
    hasCountryVariants: true,
    requiresApi: false,
    launchDate: '2025-01-01',
  },

  {
    slug: 'leave-encashment-calculator',
    category: 'hr-payroll',
    schema: 'calculator',
    featured: false,
    countries: ['uae', 'saudi', 'qatar'],
    relatedTools: ['gratuity-calculator', 'salary-calculator'],
    relatedArticles: ['annual-leave-uae-law'],
    hasCountryVariants: true,
    requiresApi: false,
    launchDate: '2025-01-01',
  },

  {
    slug: 'notice-period-calculator',
    category: 'hr-payroll',
    schema: 'calculator',
    featured: false,
    countries: ['uae', 'saudi', 'qatar', 'kuwait'],
    relatedTools: ['gratuity-calculator', 'salary-calculator'],
    relatedArticles: ['notice-period-uae-labour-law'],
    hasCountryVariants: true,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
{
  slug: 'uae-free-zone-gratuity-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-gratuity-calculator', 'salary-calculator', 'uae-domestic-worker-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'uae-leave-settlement-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['salary-calculator', 'uae-gratuity-calculator', 'uae-end-of-service-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},

{
  slug: 'uae-sick-leave-calculator',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-leave-settlement-calculator', 'salary-calculator', 'uae-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'holiday-pay-calculator-uae',
  category: 'hr-payroll',
  schema: 'calculator',
  featured: false,
  countries: ['uae'],
  relatedTools: ['uae-leave-settlement-calculator', 'uae-sick-leave-calculator', 'salary-calculator', 'uae-gratuity-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
  // ─── ISLAMIC TOOLS ────────────────────────────────────────
{
  slug: 'tola-gold-zakat-calculator',
  category: 'islamic-tools',
  schema: 'calculator',
  featured: false,
  countries: ['saudi', 'uae', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
  relatedTools: ['salary-calculator', 'profit-margin-calculator', 'loan-emi-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'salary-zakat-calculator',
  category: 'islamic-tools',
  schema: 'calculator',
  featured: false,
  countries: ['saudi', 'uae', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
  relatedTools: ['tola-gold-zakat-calculator', 'salary-calculator', 'profit-margin-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
  {
    slug: 'zakat-calculator',
    category: 'islamic-tools',
    schema: 'calculator',
    featured: true,
    countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
    relatedTools: ['hijri-gregorian-converter', 'prayer-time-calculator'],
    relatedArticles: ['how-to-calculate-zakat', 'nisab-2024-gold-silver'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
  {
    slug: 'hijri-gregorian-converter',
    category: 'islamic-tools',
    schema: 'converter',
    featured: true,
    countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
    relatedTools: ['zakat-calculator', 'prayer-time-calculator'],
    relatedArticles: ['hijri-calendar-guide'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
{
  slug: 'gold-zakat-calculator',
  category: 'islamic-tools',
  schema: 'calculator',
  featured: true,
  countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
  relatedTools: ['zakat-calculator', 'salary-calculator', 'currency-converter'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
{
  slug: 'cash-zakat-calculator',
  category: 'islamic-tools',
  schema: 'calculator',
  featured: true,
  countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
  relatedTools: ['zakat-calculator', 'gold-zakat-calculator', 'salary-calculator'],
  relatedArticles: [],
  hasCountryVariants: false,
  requiresApi: false,
  launchDate: '2025-01-01',
},
  // ─── TAX & VAT ────────────────────────────────────────────
  {
    slug: 'uae-vat-calculator',
    category: 'tax-vat',
    schema: 'calculator',
    featured: true,
    countries: ['uae'],
    relatedTools: ['ksa-vat-calculator', 'invoice-generator'],
    relatedArticles: ['uae-vat-guide-2024', 'vat-registration-uae'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
  {
    slug: 'ksa-vat-calculator',
    category: 'tax-vat',
    schema: 'calculator',
    featured: false,
    countries: ['saudi'],
    relatedTools: ['uae-vat-calculator', 'invoice-generator'],
    relatedArticles: ['ksa-vat-guide-2024'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },

  // ─── BUSINESS ─────────────────────────────────────────────
  {
    slug: 'invoice-generator',
    category: 'business',
    schema: 'generator',
    featured: true,
    countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
    relatedTools: ['uae-vat-calculator', 'profit-margin-calculator'],
    relatedArticles: ['how-to-invoice-uae', 'freelance-invoicing-gulf'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
  {
    slug: 'profit-margin-calculator',
    category: 'business',
    schema: 'calculator',
    featured: false,
    countries: ['uae', 'saudi', 'qatar', 'kuwait', 'bahrain', 'oman', 'egypt'],
    relatedTools: ['invoice-generator', 'break-even-calculator'],
    relatedArticles: ['profit-margin-guide-gulf'],
    hasCountryVariants: false,
    requiresApi: false,
    launchDate: '2025-01-01',
  },
]

// ─── Utility Functions ─────────────────────────────────────────────────────────

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug)
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return TOOLS.filter(t => t.category === categorySlug)
}

export function getFeaturedTools(): Tool[] {
  return TOOLS.filter(t => t.featured)
}

export function getToolsByCountry(country: string): Tool[] {
  return TOOLS.filter(t => t.countries.includes(country))
}

export function getRelatedTools(tool: Tool): Tool[] {
  return tool.relatedTools
    .map(slug => getToolBySlug(slug))
    .filter(Boolean) as Tool[]
}